// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © ShadowOfCrimson
//  https://www.tradingview.com/script/dsXscaGY-Expected-Volatility/


//Notes: request.security can only be called 40 times in one script, use it more sparingly to allow the script to draw
//more boxes back for backtesting... there should be a more effective way to do it...

//@version=6
indicator('Expected Volatility [Session] ', overlay = true, max_bars_back = 5000, max_boxes_count = 500)
//This indicator shows expected move sizes when correlated with each volatility index.


box_color_Res = input.color(color.new(color.green, 80),"Resitance Color",inline = "color_val")
box_color_Sup = input.color(color.new(color.red, 80),"Resitance Color",inline = "color_val")

sess_Time = input('0930-1600', 'Session Time') //Allow user to input custom session time
sess_TimeZone = input('America/New_York', 'TimeZone') //Allow user to input custom timezone
toggle = input.bool(false, "Toggle open/close")
useVOLI = input.bool(false, "Use NASDAQ:VOLI instead of VIX")
useVIX1D = input.bool(false, "Use CBOE:VIX1D instead of VIX")



close_day = (toggle and session.isfirstbar_regular)? open: close[1]
//close_day =   close[1] //The previous day's closing price
//turn this variable on to test what market the chart thinks it is on.
troubleshooting = input(false, 'Troubleshooting?')
useTF = '1D'

//  Useful function from tradingcode.net:

//  IsSessionStart() returns 'true' when the current bar is the first one
//  inside the specified session, adjusted to the given time zone (optional).
//  Returns 'false' for other bars inside the session, bars outside the
//  session, and when the time frame is 1 day or higher.
IsSessionStart(sessionTime, sessionTimeZone = syminfo.timezone) =>
    inSess = not na(time(timeframe.period, sessionTime, sessionTimeZone))
    inSess and not inSess[1]

//bgcolor(IsSessionStart("0930-1600", "GMT-4") ? color.new(color.blue, 80) : na)

//  This function takes the input volatility index and calculates variables a and b
//  a and b are used later to calculate zones based on standard deviations
GetVolatility(VolatilityIndex) =>
    a = VolatilityIndex /  math.sqrt(252) / 100 //VIX_A
    b = VolatilityIndex / math.sqrt(365) / 100 //VIX_B
    [a, b]

//  This function does all the math to generate the zones when given variables
//  a, b, and Index, where a and b are the results of GetVolatility(VolatilityIndex)
//  and Index is the Index correlated to the VolatilityIndex of interest.
Zones(a, b, Index) =>
    //Top Zone calculations:
    Index_STD1UP = Index * a //STD. DEV. 1.0 FOR Index
    Index_STD1DN = Index * b //STD. DEV. 1.0 FOR Index


    Index_ZONE1UP_Res = Index_STD1UP + Index //Upper std. dev. 1.0
    Index_ZONE1DN_Res = Index_STD1DN + Index //Lower std. dev. 1.0

    Index_ZONE150UP_Res = Index_STD1UP * 1.5 + Index //1.5 STD. DEV. ZONE UPPER
    Index_ZONE150DN_Res = Index_STD1DN * 1.5 + Index //1.5 STD. DEV. ZONE LOWER

    Index_ZONE50UP_Res = Index_STD1UP * 0.5 + Index //.5 STD. DEV. ZONE UPPER
    Index_ZONE50DN_Res = Index_STD1DN * 0.5 + Index //.5 STD. DEV. ZONE LOWER

    Index_ZONE25UP_Res = Index_STD1UP * 0.25 + Index //.25 STD. DEV. ZONE UPPER
    Index_ZONE25DN_Res = Index_STD1DN * 0.25 + Index //.25 STD. DEV. ZONE LOWER

    
    //Bottom Zone calculations:
    Index_ZONE025UP_Sup =  Index - Index_STD1DN * 0.25  //Lower std. dev. 0.5
    Index_ZONE025DN_Sup =  Index - Index_STD1UP * 0.25  //Lower std. dev. 0.5
    Index_ZONE05UP_Sup =  Index - Index_STD1DN * 0.5  //Lower std. dev. 0.5
    Index_ZONE05DN_Sup =  Index - Index_STD1UP * 0.5  //Lower std. dev. 0.5

    Index_ZONE1UP_Sup = Index - Index_STD1DN //SUBTRACT 1.0 STD. DEV. FROM PRICE
    Index_ZONE1DN_Sup = Index - Index_STD1UP //SUBTRACT 1.0 STD. DEV. FROM PRICE

    Index_ZONE150UP_Sup = Index - (Index_ZONE150DN_Res - Index)
    Index_ZONE150DN_Sup = Index - (Index_ZONE150UP_Res - Index)

    Index_ZONE50UP_Sup = Index - (Index_ZONE50DN_Res - Index)
    Index_ZONE50DN_Sup = Index - (Index_ZONE50UP_Res - Index)

    Index_ZONE25UP_Sup = Index - (Index_ZONE25DN_Res - Index)
    Index_ZONE25DN_Sup = Index - (Index_ZONE25UP_Res - Index)


    //check if the bar we're on is the start of the session according to the time and timezone variables
    if IsSessionStart(sess_Time, sess_TimeZone)

        close_time = time_close + 86400000 // time offset for creating boxes in milliseconds

        //Draw a box using all the calculated values
        line_transparency = 25

        //the first box to be drawn is the 1 std. dev. box above the settlement price
        Index_BOX_1TOP = box.new(left = time_close, top = Index_ZONE1UP_Res, right = close_time, bottom = Index_ZONE1DN_Res, xloc = xloc.bar_time, bgcolor = box_color_Sup, border_color = box_color_Sup,text ="1SD", text_size = size.normal,text_color = color.red,text_font_family = font.family_monospace) 
        line.new(time_close,Index_ZONE1DN_Res+ (Index_ZONE1UP_Res-Index_ZONE1DN_Res)/2,close_time,Index_ZONE1DN_Res+ (Index_ZONE1UP_Res-Index_ZONE1DN_Res)/2,xloc = xloc.bar_time,color=color.new(color.red, line_transparency),style=line.style_dashed,width=1)
        //the box should be red and as transparent as the user indicates it to be
        //this box is the 1 std. dev. box below the settlement price
        Index_BOX_1BTM = box.new(left = time_close, top = Index_ZONE1DN_Sup, right = close_time, bottom = Index_ZONE1UP_Sup, xloc = xloc.bar_time, bgcolor = box_color_Res, border_color = box_color_Res,text ="1SD", text_size = size.normal,text_color = color.green,text_font_family = font.family_monospace) 
        line.new(time_close,Index_ZONE1DN_Sup+ (Index_ZONE1UP_Sup-Index_ZONE1DN_Sup)/2,close_time,Index_ZONE1DN_Sup+ (Index_ZONE1UP_Sup-Index_ZONE1DN_Sup)/2,xloc = xloc.bar_time,color=color.new(color.green, line_transparency),style=line.style_dashed,width=1)
        //this is the 1.5 std. dev. box above the settlement price
        Index_BOX_2TOP = box.new(left = time_close, top = Index_ZONE150UP_Res, right = close_time, bottom = Index_ZONE150DN_Res, xloc = xloc.bar_time, bgcolor = box_color_Sup, border_color = box_color_Sup)
        line.new(time_close,Index_ZONE150DN_Res+ (Index_ZONE150UP_Res-Index_ZONE150DN_Res)/2,close_time,Index_ZONE150DN_Res+ (Index_ZONE150UP_Res-Index_ZONE150DN_Res)/2,xloc = xloc.bar_time,color=color.new(color.red, line_transparency),style=line.style_dashed,width=1)
        //this is the 1.5 std. dev. box below the settlement price
        Index_BOX_2BTM = box.new(left = time_close, top = Index_ZONE150DN_Sup, right = close_time, bottom = Index_ZONE150UP_Sup, xloc = xloc.bar_time, bgcolor = box_color_Res, border_color = box_color_Res)
        line.new(time_close,Index_ZONE150DN_Sup+ (Index_ZONE150UP_Sup-Index_ZONE150DN_Sup)/2,close_time,Index_ZONE150DN_Sup+ (Index_ZONE150UP_Sup-Index_ZONE150DN_Sup)/2,xloc = xloc.bar_time,color=color.new(color.green, line_transparency),style=line.style_dashed,width=1)
        //this is the 0.5 std. dev. box above the settlement price
        Index_BOX_3TOP = box.new(left = time_close, top = Index_ZONE50UP_Res, right = close_time, bottom = Index_ZONE50DN_Res, xloc = xloc.bar_time, bgcolor = box_color_Sup, border_color = box_color_Sup)
        line.new(time_close,Index_ZONE50DN_Res+ (Index_ZONE50UP_Res-Index_ZONE50DN_Res)/2,close_time,Index_ZONE50DN_Res+ (Index_ZONE50UP_Res-Index_ZONE50DN_Res)/2,xloc = xloc.bar_time,color=color.new(color.red, line_transparency),style=line.style_dashed,width=1)
        //this is the 0.5 std. dev. box below the settlement price
        Index_BOX_3BTM = box.new(left = time_close, top = Index_ZONE50DN_Sup, right = close_time, bottom = Index_ZONE50UP_Sup, xloc = xloc.bar_time, bgcolor = box_color_Res, border_color = box_color_Res)
        line.new(time_close,Index_ZONE50DN_Sup+ (Index_ZONE50UP_Sup-Index_ZONE50DN_Sup)/2,close_time,Index_ZONE50DN_Sup+ (Index_ZONE50UP_Sup-Index_ZONE50DN_Sup)/2,xloc = xloc.bar_time,color=color.new(color.green, line_transparency),style=line.style_dashed,width=1)
        //this is the 0.25 std. dev. box above the settlement price
        Index_BOX_4TOP = box.new(left = time_close, top = Index_ZONE25UP_Res, right = close_time, bottom = Index_ZONE25DN_Res, xloc = xloc.bar_time, bgcolor = box_color_Sup, border_color = box_color_Sup)
        line.new(time_close,Index_ZONE25DN_Res+ (Index_ZONE25UP_Res-Index_ZONE25DN_Res)/2,close_time,Index_ZONE25DN_Res+ (Index_ZONE25UP_Res-Index_ZONE25DN_Res)/2,xloc = xloc.bar_time,color=color.new(color.red, line_transparency),style=line.style_dashed,width=1)
        //this is the 0.25 std. dev. box below the settlement price
        Index_BOX_4BTM = box.new(left = time_close, top = Index_ZONE25DN_Sup, right = close_time, bottom = Index_ZONE25UP_Sup, xloc = xloc.bar_time, bgcolor = box_color_Res, border_color = box_color_Res)
        line.new(time_close,Index_ZONE25DN_Sup+ (Index_ZONE25UP_Res-Index_ZONE25DN_Res)/2,close_time,Index_ZONE25DN_Sup+ (Index_ZONE25UP_Res-Index_ZONE25DN_Res)/2,xloc = xloc.bar_time,color=color.new(color.green, line_transparency),style=line.style_dashed,width=1)
        Index_BOX_4BTM

    //return the values after the function is done:
    [a, b, Index]



var ES = 0.0
var NQ = 0.0
var CL = 0.0
var RTY = 0.0
//var VVIX = 0.0
var GC = 0.0
var SI = 0.0
var YM = 0.0

var VIX = 0.0
var VXN = 0.0
var OVX = 0.0
var RVX = 0.0
var VVIX = 0.0
var GVZ = 0.0
var VXSLV = 0.0
var VXD = 0.0


//  Market and Volatility Index pairs begin:

//Here, we check which chart we are using to determine what zones to calculate:
//If we are on ES1!, we use the VIX and then calculate zones using a, b, and ES
if str.contains(syminfo.ticker, 'ES') or str.contains(syminfo.ticker, 'SPY') or str.contains(syminfo.ticker, 'SPX')//and IsSessionStart(sess_Time, sess_TimeZone) //ticker.standard(syminfo.tickerid) == 'CME_MINI:ES1!'
    //xc
    //  ES & VIX
    //  Request the previous day's settlement on ES
    ES := request.security(syminfo.tickerid, useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true) //function to request data from a different chart "CME_MINI:ES1!",   //the name of the security requested "1D",  //the timeframe of the request close_day, //the time requested gaps = barmerge.gaps_off,  //merge strategy for requested data lookahead = barmerge.lookahead_on  //merge strategy for the requested data position )
    //  Request the previous day's settlement on VIX
    VIX := request.security(useVOLI? 'NASDAQ:VOLI' :useVIX1D? 'CBOE:VIX1D' :'CBOE:VIX', useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true)

    [VIX_A, VIX_B] = GetVolatility(VIX)

    Zones(VIX_A, VIX_B, ES)
    //if troubleshooting is on, and we see the index is ES1!, label it as such
    if troubleshooting == true
        label.new(timenow, close, 'ES', xloc = xloc.bar_time)

        //If we are on NQ1!, we use the VXN and then calculate zones using a, b, and NQ
else if str.contains(syminfo.ticker, 'NQ') or str.contains(syminfo.ticker, 'QQQ')

    //  NQ & VXN
    //  Request the previous day's settlement on NQ
    NQ := request.security(syminfo.tickerid, useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true)
    //  Request the previous day's settlement on VXN
    VXN := request.security('CBOE:VXN', useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true)

    [VXN_A, VXN_B] = GetVolatility(VXN)
    Zones(VXN_A, VXN_B, NQ)
    if troubleshooting == true
        label.new(timenow, close, 'NQ', xloc = xloc.bar_time)
        //If we are on CL1!, we use the OVX and then calculate zones using a, b, and CL
else if str.contains(syminfo.ticker, 'CL')
    //  CL & OVX
    //  Request the previous day's settlement on CL
    CL := request.security('NYMEX:CL1!', useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true)

    //  Request the previous day's settlement on OVX
    OVX := request.security('CBOE:OVX', useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true)

    [OVX_A, OVX_B] = GetVolatility(OVX)

    Zones(OVX_A, OVX_B, CL)
    if troubleshooting == true
        label.new(timenow, close, 'CL', xloc = xloc.bar_time)
        //If we are on RTY1!, we use the RVX and then calculate zones using a, b, and RTY
else if str.contains(syminfo.ticker, 'RTY') or str.contains(syminfo.ticker, 'M2K') or str.contains(syminfo.ticker, 'IWM')
    //  RTY & RVX
    //  Request the previous day's settlement on RTY
    RTY := request.security(syminfo.tickerid, useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true)
    //  Request the previous day's settlement on RVX
    RVX := request.security('CBOE:RVX', useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true)

    [RVX_A, RVX_B] = GetVolatility(RVX)
    Zones(RVX_A, RVX_B, RTY)
    if troubleshooting == true
        label.new(timenow, close, 'RTY', xloc = xloc.bar_time)
        //If we are on VIX, we use the VVIX and then calculate zones using a, b, and VIX
else if ticker.standard(syminfo.tickerid) == 'CBOE:VIX'
    
    //  VIX & VVIX
    //  Request the previous day's settlement on VVIX
    VVIX := request.security('CBOE:VVIX', useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true)
    [VVIX_A, VVIX_B] = GetVolatility(VVIX)
    Zones(VVIX_A, VVIX_B, VIX)
    if troubleshooting == true
        label.new(timenow, close, 'VIX', xloc = xloc.bar_time)
        //If we are on GC1!, we use the GVZ and then calculate zones using a, b, and GC
else if str.contains(syminfo.ticker, 'GC')
    //  GC & GVZ
    //  Request the previous day's settlement on GC
    GC := request.security('COMEX:GC1!', useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true)

    //  Request the previous day's settlement on GVZ
    GVZ := request.security('CBOE:GVZ', useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true)
    [GVZ_A, GVZ_B] = GetVolatility(GVZ)
    Zones(GVZ_A, GVZ_B, GC)
    if troubleshooting == true
        label.new(timenow, close, 'GC', xloc = xloc.bar_time)
        //If we are on SILVER1!, we use the VXSLV and then calculate zones using a, b, and SI
        //Note: the volatility index for silver is discontinued.
else if str.contains(syminfo.ticker, 'SI')
    //  SI & VXSLV
    //  Request the previous day's settlement on SI
    SI := request.security('COMEX:SI1!', useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on)
    //  Request the previous day's settlement on VXSLV
    VXSLV := request.security('CBOE:VXSLV', useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true)
    [VXSLV_A, VXSLV_B] = GetVolatility(VXSLV)
    Zones(VXSLV_A, VXSLV_B, SI)
    if troubleshooting == true
        label.new(timenow, close, 'SILVER', xloc = xloc.bar_time)
        //If we are on YM1!, we use the VXD and then calculate zones using a, b, and YM
else if str.contains(syminfo.ticker, 'YM') or str.contains(syminfo.ticker, 'DIA')
    //  YM & VXD
    //  Request the previous day's settlement on YM
    YM := request.security(syminfo.tickerid, useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true)//function to request data from a different chart "CBOT_MINI:YM1!",   //the name of the security requested "1D",  //the timeframe of the request close_day, //the time requested gaps = barmerge.gaps_off,  //merge strategy for requested data lookahead = barmerge.lookahead_on  //merge strategy for the requested data position )
    //  Request the previous day's settlement on VXD
    VXD := request.security('CBOE:VXD', useTF, close_day, gaps = barmerge.gaps_off, lookahead = barmerge.lookahead_on,ignore_invalid_symbol = true)
    
    [VXD_A, VXD_B] = GetVolatility(VXD)
    Zones(VXD_A, VXD_B, YM)
    if troubleshooting == true
        label.new(timenow, close, 'YM', xloc = xloc.bar_time)
else //If we don't recognize the chart and we're troubleshooting, make a label signifying this.
    if troubleshooting == true
        label.new(timenow, close, 'NOT RECOGNIZED.', xloc = xloc.bar_time)


//  Market and Volatility Index pairs end


//  plot an invisible ES chart to see the values in the data window during troubleshooting
plotES = plot(ES, 'ES', color = color.new(color.white, 100), display = display.data_window)
//  plot an invisible VIX chart to see the values in the data window during troubleshooting
plotVIX = plot(VIX, 'VIX', color = color.new(color.white, 100), display = display.data_window)

//  plot an invisible ES chart to see the values in the data window during troubleshooting
plotYM = plot(YM, 'YM', color = color.new(color.white, 100), display = display.data_window)
//  plot an invisible VXD chart to see the values in the data window during troubleshooting
plotVXD = plot(VXD, 'VXD', color = color.new(color.white, 100), display = display.data_window)
//  plot an invisible SI chart to see the values in the data window during troubleshooting
plotSI = plot(SI, 'SI', color = color.new(color.white, 100), display = display.data_window)
//  plot an invisible VXSLV chart to see the values in the data window during troubleshooting
plotVXSLV = plot(VXSLV, 'VXSLV', color = color.new(color.white, 100), display = display.data_window)

//  plot an invisible GC chart to see the values in the data window during troubleshooting
plotGC = plot(GC, 'GC', color = color.new(color.white, 100), display = display.data_window)
//  plot an invisible GVZ chart to see the values in the data window during troubleshooting
plotGVZ = plot(GVZ, 'GVZ', color = color.new(color.white, 100), display = display.data_window)

//  plot an invisible RVX chart to see the values in the data window during troubleshooting
plotRVX = plot(RVX, 'RVX', color = color.new(color.white, 100), display = display.data_window)
//  plot an invisible VVIX chart to see the values in the data window during troubleshooting
plotVVIX = plot(VVIX, 'VVIX', color = color.new(color.white, 100), display = display.data_window)

//  plot an invisible RTY chart to see the values in the data window during troubleshooting
plotRTY = plot(RTY, 'RTY', color = color.new(color.white, 100), display = display.data_window)

//  plot an invisible NQ chart to see the values in the data window during troubleshooting
plotNQ = plot(NQ, 'NQ', color = color.new(color.white, 100), display = display.data_window)
//  plot an invisible VXN chart to see the values in the data window during troubleshooting
plotVXN = plot(VXN, 'VXN', color = color.new(color.white, 100), display = display.data_window)
//  plot an invisible CL chart to see the values in the data window during troubleshooting
plotCL = plot(CL, 'CL', color = color.new(color.white, 100), display = display.data_window)

//  plot an invisible OVX chart to see the values in the data window during troubleshooting
plotOVX = plot(OVX, 'OVX', color = color.new(color.white, 100), display = display.data_window)