"""Generate `scripts/ninjatrader/shared/DecisionLog.cs` from the frozen schema.

Same reasoning as `generate_trading_defaults.py`: the column list exists in
exactly one place (`reporting/decision_log.py`), and the C# writer is generated
from it so a column added on the Python side cannot leave the bot emitting a
file the reader refuses. A hand-maintained second copy of a CSV header is the
drift this whole exercise removes.

    python scripts/utils/generate_decision_log.py           # write
    python scripts/utils/generate_decision_log.py --check   # verify only

WHY THE BOT WRITES THIS AND NOT THE BRIDGE. The bridge can report what NT8
knows: fills, prices, P&L, MAE. It cannot report which criteria a strategy
evaluated, because that lives in the strategy's own code and is never handed to
the platform. No MCP change can produce a "why" -- so the emitter has to be in
the bot, and the only question is where it writes.

WHERE IT WRITES, AND WHY THAT NEEDS NO BRIDGE CHANGE. `Globals.UserDataDir`
with an `mcp_` prefix and a `.csv` suffix, because the bridge's existing
`nt_list_exports` / `nt_get_export` / `nt_delete_export` endpoints already serve
exactly that filename shape behind a path-traversal gate. The precedent to avoid
is the existing per-bar dump in `BBMRReversionBot`, which writes
`%TEMP%/bbmr_diag_<guid>.csv` and prints the path ONLY to the NT8 output window:
the data exists and is unaddressable, which is indistinguishable from not
having it.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

# Invoked as a PATH by test_decision_log.py (matching how the trading-defaults
# generator is called), so the repo root is not on sys.path by construction.
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))

from scripts.trading_framework.reporting.decision_log import (
    COLUMNS, DECISIONS, SCHEMA_VERSION,
)

REPO = pathlib.Path(__file__).resolve().parents[2]
OUT = REPO / "scripts" / "ninjatrader" / "shared" / "DecisionLog.cs"


def render() -> str:
    L: list[str] = []
    a = L.append
    a("// GENERATED FILE -- DO NOT EDIT.")
    a("//")
    a("// Source : scripts/trading_framework/reporting/decision_log.py (COLUMNS)")
    a("// Tool   : scripts/utils/generate_decision_log.py")
    a("// Spec   : docs/architecture/STRATEGY_WORKFLOW.md section 5.1")
    a("//")
    a("// Edit the Python schema and re-run the tool. A hand edit here is reverted")
    a("// by the next generation and fails test_decision_log.py in the meantime.")
    a("//")
    a("// WHAT THIS IS FOR: a trade list says what happened; only the strategy can")
    a("// say WHY. The gate roster this emits is also the cheapest parity check")
    a("// there is -- two sides evaluating different criteria are two strategies,")
    a("// and a trade-set recall between them is a number about nothing.")
    a("//")
    a("// FOUR RULES, each a failure mode of the per-bar dump this replaces:")
    a("//   1. Log DECISIONS, not bars. Rows are bounded by triggers x gates.")
    a("//   2. Record EVERY gate. `&&` stops early, so a first-failure log")
    a("//      reports the short-circuit ORDER as the cause. Gate() is called")
    a("//      before the verdict for exactly this reason.")
    a("//   3. Record the VALUE, not just pass/fail. \"ADX passed\" is not")
    a("//      analysable; \"ADX 18.2 vs 15\" says the trade was marginal.")
    a("//   4. Rejections need a DENOMINATOR -- Skip() counts bars that never")
    a("//      triggered, or \"gate X blocked 40 setups\" has no scale.")
    a("")
    a("using System;")
    a("using System.Collections.Generic;")
    a("using System.Globalization;")
    a("using System.IO;")
    a("using System.Text;")
    a("")
    a("namespace NinjaTrader.NinjaScript.Strategies.Vinay")
    a("{")
    a("    /// <summary>One named criterion, its outcome, and the numbers behind it.</summary>")
    a("    public struct DecisionGate")
    a("    {")
    a("        public string Name;")
    a("        public bool   Passed;")
    a("        public double Value;")
    a("        public double Threshold;")
    a("        public bool   HasValue;")
    a("        public bool   HasThreshold;")
    a("        public string Detail;")
    a("        /// <summary>\"gate\" blocks and enters the roster; \"measure\" is a")
    a("        /// covariate that never blocks. Recording a magnitude as a gate")
    a("        /// produces a 0%-failure gate -- a green that can never be red.</summary>")
    a("        public string Kind;")
    a("    }")
    a("")
    a("    /// <summary>")
    a("    /// One decision under construction. Gates are added BEFORE the verdict so")
    a("    /// that every one is evaluated (rule 2); a verdict taken first would let")
    a("    /// the caller short-circuit and record only the earliest failure.")
    a("    /// </summary>")
    a("    public class DecisionBuilder")
    a("    {")
    a("        private readonly DecisionLog log;")
    a("        private readonly DateTime   barTime;")
    a("        private readonly string     direction;")
    a("        private readonly List<DecisionGate> gates = new List<DecisionGate>();")
    a("")
    a("        internal DecisionBuilder(DecisionLog log, DateTime barTime, string direction)")
    a("        { this.log = log; this.barTime = barTime; this.direction = direction ?? \"\"; }")
    a("")
    a("        public DecisionBuilder Gate(string name, bool passed)")
    a("        { return Add(name, passed, 0, false, 0, false, null, \"gate\"); }")
    a("")
    a("        public DecisionBuilder Gate(string name, bool passed, double value)")
    a("        { return Add(name, passed, value, true, 0, false, null, \"gate\"); }")
    a("")
    a("        public DecisionBuilder Gate(string name, bool passed, double value, double threshold)")
    a("        { return Add(name, passed, value, true, threshold, true, null, \"gate\"); }")
    a("")
    a("        /// <summary>A covariate for the win/loss analysis. NEVER blocks, and")
    a("        /// never enters the roster: recording \"close is past the band\" as a")
    a("        /// gate on bars that triggered BECAUSE the close is past the band gives")
    a("        /// a gate with a structural 0% failure rate.</summary>")
    a("        public DecisionBuilder Measure(string name, double value)")
    a("        { return Add(name, true, value, true, 0, false, null, \"measure\"); }")
    a("")
    a("        public DecisionBuilder Measure(string name, double value, double threshold)")
    a("        { return Add(name, true, value, true, threshold, true, null, \"measure\"); }")
    a("")
    a("        public DecisionBuilder Note(string name, bool passed, string detail)")
    a("        { return Add(name, passed, 0, false, 0, false, detail, \"note\"); }")
    a("")
    a("        /// <summary>Append a gate built elsewhere. This is how GovernedStrategy")
    a("        /// forwards what the subclass declared into the SAME decision the base")
    a("        /// then adds its own governance gates to -- one decision, one row set,")
    a("        /// so a framework refusal and a strategy refusal are comparable.</summary>")
    a("        public DecisionBuilder Add(DecisionGate g)")
    a("        {")
    a("            if (string.IsNullOrWhiteSpace(g.Name)) g.Name = \"unnamed\";")
    a("            if (string.IsNullOrWhiteSpace(g.Kind)) g.Kind = \"gate\";")
    a("            gates.Add(g);")
    a("            return this;")
    a("        }")
    a("")
    a("        private DecisionBuilder Add(string name, bool passed, double value, bool hasValue,")
    a("                                    double threshold, bool hasThreshold, string detail,")
    a("                                    string kind)")
    a("        {")
    a("            if (string.IsNullOrWhiteSpace(name))")
    a("                name = \"unnamed\";   // never drop a gate; an unnamed one is still a row")
    a("            gates.Add(new DecisionGate {")
    a("                Name = name, Passed = passed, Value = value, Threshold = threshold,")
    a("                HasValue = hasValue, HasThreshold = hasThreshold, Detail = detail,")
    a("                Kind = kind });")
    a("            return this;")
    a("        }")
    a("")
    a("        /// <summary>Every gate passed and the order was submitted.</summary>")
    a("        /// <param name=\"signalName\">The NT8 order signal name. It is the JOIN KEY")
    a("        /// to the fill (Execution.Name), so it MUST be unique per entry -- a")
    a("        /// constant name makes every entry indistinguishable downstream.</param>")
    a("        public void Entry(string signalName) { log.Write(barTime, \"ENTRY\", direction, signalName, gates); }")
    a("")
    a("        /// <summary>A setup existed and a gate stopped it.</summary>")
    a("        public void Reject() { log.Write(barTime, \"REJECTED\", direction, \"\", gates); }")
    a("")
    a("        /// <summary>True when no gate failed -- so the caller can branch on the")
    a("        /// SAME data it logged, rather than re-evaluating the conditions and")
    a("        /// risking a log that disagrees with the behaviour it describes.</summary>")
    a("        public bool AllPassed")
    a("        {")
    a("            get {")
    a("                foreach (var g in gates)")
    a("                    if (g.Kind == \"gate\" && !g.Passed) return false;")
    a("                return true;")
    a("            }")
    a("        }")
    a("    }")
    a("")
    a("    /// <summary>")
    a("    /// Appends decision rows to an mcp_*.csv in Globals.UserDataDir, which the")
    a("    /// bridge's existing nt_get_export endpoint already serves. Never throws into")
    a("    /// the strategy: a logging failure must not kill a backtest. It is not silent")
    a("    /// either -- LastError is set and printed once, because a logger that fails")
    a("    /// quietly produces a short file that reads as \"the strategy took no trades\".")
    a("    /// </summary>")
    a("    public class DecisionLog : IDisposable")
    a("    {")
    a("        public const int    SchemaVersion = {};".format(SCHEMA_VERSION))
    a("        public const string FilePrefix    = \"mcp_decisions_\";")
    a("")
    _emit_header(a)
    a("")
    a("        public string Path      { get; private set; }")
    a("        public string LastError { get; private set; }")
    a("        public int    Skipped   { get; private set; }")
    a("        public int    Bars      { get; private set; }")
    a("")
    a("        private readonly string runId;")
    a("        private readonly string strategy;")
    a("        private StreamWriter    w;")
    a("        private int             seq;")
    a("        private bool            printed;")
    a("")
    a("        // Instance counter: the Strategy Analyzer runs many instances of one")
    a("        // strategy CONCURRENTLY during an optimisation, and two of them opening")
    a("        // the same path is a truncated file rather than an error.")
    a("        private static int instances;")
    a("")
    a("        public DecisionLog(string strategyName, string runId)")
    a("        {")
    a("            this.strategy = strategyName ?? \"unknown\";")
    a("            this.runId    = string.IsNullOrWhiteSpace(runId) ? \"na\" : runId;")
    a("            try")
    a("            {")
    a("                int n = System.Threading.Interlocked.Increment(ref instances);")
    a("                string name = string.Format(CultureInfo.InvariantCulture,")
    a("                    \"{0}{1}_{2}_{3:D3}.csv\", FilePrefix, Sanitize(this.strategy),")
    a("                    DateTime.Now.ToString(\"yyyyMMdd_HHmmss\", CultureInfo.InvariantCulture), n);")
    a("                Path = System.IO.Path.Combine(NinjaTrader.Core.Globals.UserDataDir, name);")
    a("                w = new StreamWriter(Path, false, new UTF8Encoding(false));")
    a("                w.WriteLine(Header);")
    a("                w.Flush();")
    a("            }")
    a("            catch (Exception ex) { LastError = ex.Message; w = null; }")
    a("        }")
    a("")
    a("        /// <summary>Start a decision. Add gates, then call Entry or Reject.</summary>")
    a("        public DecisionBuilder Decision(DateTime barTime, string direction)")
    a("        { return new DecisionBuilder(this, barTime, direction); }")
    a("")
    a("        /// <summary>A bar that produced no setup at all. Counted, not written --")
    a("        /// the denominator is what rule 4 needs, and a row per quiet bar would be")
    a("        /// the per-bar dump this class exists to replace.</summary>")
    a("        public void Skip() { Bars++; Skipped++; }")
    a("")
    a("        /// <summary>A bar that produced a setup. Counts toward Bars only.</summary>")
    a("        public void Bar() { Bars++; }")
    a("")
    a("        internal void Write(DateTime barTime, string decision, string direction,")
    a("                            string signalName, List<DecisionGate> gates)")
    a("        {")
    a("            if (w == null) return;")
    a("            seq++;")
    a("            try")
    a("            {")
    a("                string stamp   = barTime.ToString(\"yyyy-MM-ddTHH:mm:ss\", CultureInfo.InvariantCulture);")
    a("                string session = TradingDefaults.SessionFor(barTime.Hour * 100 + barTime.Minute);")
    a("                if (gates == null || gates.Count == 0)")
    a("                {")
    a("                    Row(stamp, session, direction, decision, signalName, \"\", \"note\",")
    a("                        decision != \"REJECTED\", \"\", \"\", \"\");")
    a("                }")
    a("                else")
    a("                {")
    a("                    foreach (var g in gates)")
    a("                        Row(stamp, session, direction, decision, signalName, g.Name,")
    a("                            string.IsNullOrEmpty(g.Kind) ? \"gate\" : g.Kind, g.Passed,")
    a("                            g.HasValue     ? Num(g.Value)     : \"\",")
    a("                            g.HasThreshold ? Num(g.Threshold) : \"\",")
    a("                            g.Detail ?? \"\");")
    a("                }")
    a("                // Flush per DECISION, not per bar. An SA run that is cancelled, or a")
    a("                // strategy that throws, otherwise loses the tail -- and the tail is")
    a("                // where the interesting decisions are.")
    a("                w.Flush();")
    a("            }")
    a("            catch (Exception ex) { LastError = ex.Message; }")
    a("        }")
    a("")
    a("        private void Row(string stamp, string session, string direction, string decision,")
    a("                         string signalName, string gate, string kind, bool pass,")
    a("                         string value, string threshold, string detail)")
    a("        {")
    a("            w.WriteLine(string.Join(\",\", new string[] {")
    a("                SchemaVersion.ToString(CultureInfo.InvariantCulture),")
    a("                Q(runId), \"nt8\", Q(strategy),")
    a("                seq.ToString(CultureInfo.InvariantCulture),")
    a("                stamp, Q(session), Q(direction), decision, Q(signalName), Q(gate),")
    a("                kind, pass ? \"1\" : \"0\", value, threshold, Q(detail) }));")
    a("        }")
    a("")
    a("        /// <summary>Emits the SKIP denominator row. Call from OnTermination.</summary>")
    a("        public void Dispose()")
    a("        {")
    a("            if (w == null) return;")
    a("            try")
    a("            {")
    a("                w.WriteLine(string.Join(\",\", new string[] {")
    a("                    SchemaVersion.ToString(CultureInfo.InvariantCulture),")
    a("                    Q(runId), \"nt8\", Q(strategy), \"0\", \"\", \"\", \"\", \"SKIP\", \"\", \"\",")
    a("                    \"note\", \"1\",")
    a("                    Skipped.ToString(CultureInfo.InvariantCulture),")
    a("                    Bars.ToString(CultureInfo.InvariantCulture),")
    a("                    Q(\"bars with no trigger of any kind (rule 4 denominator)\") }));")
    a("                w.Flush(); w.Close();")
    a("            }")
    a("            catch (Exception ex) { LastError = ex.Message; }")
    a("            finally { w = null; }")
    a("        }")
    a("")
    a("        /// <summary>What to Print() once, so an operator can FIND the file. The")
    a("        /// existing per-bar dump printed a %TEMP% GUID path and nothing else,")
    a("        /// which is data that exists and cannot be addressed.</summary>")
    a("        public string Banner()")
    a("        {")
    a("            printed = true;")
    a("            if (LastError != null)")
    a("                return \"[DECISIONLOG] DISABLED: \" + LastError;")
    a("            return \"[DECISIONLOG] \" + System.IO.Path.GetFileName(Path)")
    a("                 + \" (fetch with nt_get_export)\";")
    a("        }")
    a("")
    a("        public bool Printed { get { return printed; } }")
    a("")
    a("        private static string Num(double v)")
    a("        {")
    a("            if (double.IsNaN(v) || double.IsInfinity(v)) return \"\";")
    a("            return v.ToString(\"G6\", CultureInfo.InvariantCulture);")
    a("        }")
    a("")
    a("        // A gate name or a detail containing a comma would shift every column to")
    a("        // its right, and the Python reader would refuse the file -- which is the")
    a("        // good outcome, but only after a wasted run. Quote instead.")
    a("        private static string Q(string s)")
    a("        {")
    a("            if (string.IsNullOrEmpty(s)) return \"\";")
    a("            if (s.IndexOf(',') < 0 && s.IndexOf('\"') < 0 && s.IndexOf('\\n') < 0) return s;")
    a("            return \"\\\"\" + s.Replace(\"\\\"\", \"\\\"\\\"\") + \"\\\"\";")
    a("        }")
    a("")
    a("        private static string Sanitize(string s)")
    a("        {")
    a("            var sb = new StringBuilder();")
    a("            foreach (var c in s)")
    a("                sb.Append(char.IsLetterOrDigit(c) || c == '_' || c == '-' ? c : '_');")
    a("            return sb.ToString();")
    a("        }")
    a("    }")
    a("}")
    return "\n".join(L) + "\n"


def _emit_header(a) -> None:
    a("        // The column order IS the schema. Generated from decision_log.COLUMNS.")
    a("        public const string Header =")
    parts = list(COLUMNS)
    for i, c in enumerate(parts):
        sep = "" if i == len(parts) - 1 else ","
        tail = ";" if i == len(parts) - 1 else ""
        a('            "{}{}"{}'.format(c, sep, tail) if i == 0 else
          '            + "{}{}"{}'.format(c, sep, tail))
    a("")
    a("        // Recognised decision values, mirrored from decision_log.DECISIONS.")
    a("        public static readonly string[] Decisions = new string[] {{ {} }};".format(
        ", ".join('"{}"'.format(d) for d in DECISIONS)))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the committed file matches; write nothing")
    args = ap.parse_args()
    text = render()
    if args.check:
        if not OUT.exists():
            print("MISSING: {}".format(OUT.relative_to(REPO)))
            return 1
        cur = OUT.read_text(encoding="utf-8")
        if cur != text:
            print("DRIFT: {} does not match the schema in "
                  "reporting/decision_log.py. Re-run without --check."
                  .format(OUT.relative_to(REPO)))
            return 1
        print("OK: {} matches decision_log.COLUMNS ({} columns)"
              .format(OUT.relative_to(REPO), len(COLUMNS)))
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print("wrote {} ({} columns, schema v{})"
          .format(OUT.relative_to(REPO), len(COLUMNS), SCHEMA_VERSION))
    return 0


if __name__ == "__main__":
    sys.exit(main())
