"use server";

import fs from 'fs/promises';
import path from 'path';

export async function getLiveChartData() {
    try {
        // Path to the JSON file generated by python script
        const filePath = path.join(process.cwd(), '..', 'data', 'live_chart.json');

        // Check availability
        try {
            await fs.access(filePath);
        } catch {
            return { success: false, error: 'Live data not available (Script not running?)' };
        }

        const content = await fs.readFile(filePath, 'utf-8');
        const data = JSON.parse(content);

        return { success: true, data };
    } catch (error: any) {
        return { success: false, error: error.message };
    }
}
