import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const ticker = searchParams.get('ticker') || 'ES';
  
  // Path to the data generated by l2_processor_engine.py
  // Assuming the engine runs from the root and writes to data/live/
  const filePath = path.join(process.cwd(), 'data', 'live', `heatmap_${ticker}.json`);

  try {
    if (fs.existsSync(filePath)) {
      const fileContent = fs.readFileSync(filePath, 'utf8');
      return NextResponse.json(JSON.parse(fileContent));
    } else {
      return NextResponse.json([], { status: 404 });
    }
  } catch (error) {
    return NextResponse.json({ error: 'Failed to read heatmap data' }, { status: 500 });
  }
}
