"""
Daily Context Join

Enriches the macro DataFrame with fields from ``daily_context_{symbol}.parquet``
(generated by lib/context.py).  This is the Phase 2 retrofit described in the
Market Analytics Platform Spec section 4.2.1.

Fields added (only those not already present in macro_records):
    gap_direction, gap_size_bucket, gap_filled, gap_fill_time_minutes,
    atr_14d, session_range, atr_usage_pct, atr_respected,
    open_vs_pd_range, is_inside_day, is_outside_day,
    session_close, session_direction,
    pdh_broken, pdl_broken, both_pd_broken,
    pdh_break_time_minutes, pdl_break_time_minutes,
    streak_length, streak_direction,
    is_event_day, event_type,
    prior_week_high, prior_week_low, prior_week_close, weekly_open,
    vix_pctile_60d,
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

import pandas as pd

logger = logging.getLogger(__name__)

# Columns from daily_context that should be joined (skip those already in macros)
_CONTEXT_COLS = [
    "trading_date",
    # VIX (only add pctile — vix_regime / vix_close already in macro pipeline)
    "vix_pctile_60d",
    # ATR
    "atr_14d",
    "session_range",
    "atr_usage_pct",
    "atr_respected",
    # Gap
    "gap_direction",
    "gap_size_bucket",
    "gap_size_points",
    "gap_size_pct",
    "gap_filled",
    "gap_fill_time_minutes",
    # Overnight / globex
    "overnight_high",
    "overnight_low",
    "midnight_open",
    # Open context
    "open_vs_pd_range",
    "open_vs_midnight",
    "is_inside_day",
    "is_outside_day",
    # Session outcome
    "session_close",
    "session_direction",
    # PD level breaks (day-level — whether PDH/PDL was broken at all today)
    "pdh_broken",
    "pdl_broken",
    "both_pd_broken",
    "pdh_break_time_minutes",
    "pdl_break_time_minutes",
    # Streaks
    "streak_length",
    "streak_direction",
    # Events
    "is_event_day",
    "event_type",
    "is_opex_week",
    # DOW (may already be in macro records; never-overwrite guards handle it)
    "day_of_week",
    # Weekly
    "prior_week_high",
    "prior_week_low",
    "prior_week_close",
    "weekly_open",
]

# Daily-context symbol matches EDgeful macro instrument names directly
_SYMBOL_MAP: dict[str, str] = {}  # empty → identity (NQ1 → NQ1)


def _resolve_symbol(instrument: str) -> str:
    return _SYMBOL_MAP.get(instrument, instrument)


def join_daily_context(
    df_macro: pd.DataFrame,
    instrument: str,
    derived_dir: Optional[Path] = None,
) -> pd.DataFrame:
    """
    Left-join ``daily_context_{instrument}.parquet`` onto *df_macro*.

    Parameters
    ----------
    df_macro   : The macro records DataFrame for a single instrument.
                 Must contain a ``trading_date`` column compatible with
                 daily_context (string "YYYY-MM-DD" or datetime).
    instrument : Symbol string, e.g. "NQ1".
    derived_dir: Path to ``data/derived/``.  If None, resolved relative
                 to this file's location (3 levels up → repo root).

    Returns
    -------
    Enriched DataFrame with daily_context columns appended.  Columns already
    present in df_macro are **not** overwritten.
    """
    if derived_dir is None:
        derived_dir = Path(__file__).parent.parent.parent.parent / "data" / "derived"

    symbol    = _resolve_symbol(instrument)
    ctx_path  = derived_dir / f"daily_context_{symbol}.parquet"

    if not ctx_path.exists():
        logger.warning(
            "join_daily_context: %s not found — skipping context join for %s",
            ctx_path, instrument,
        )
        return df_macro

    ctx = pd.read_parquet(ctx_path)

    # Select only columns that exist in the file
    available = [c for c in _CONTEXT_COLS if c in ctx.columns]
    ctx = ctx[available].copy()

    # Normalise trading_date to string "YYYY-MM-DD" for merge
    ctx["trading_date"] = pd.to_datetime(ctx["trading_date"]).dt.strftime("%Y-%m-%d")

    # Normalise macro trading_date to same string format
    df = df_macro.copy()
    df["trading_date"] = pd.to_datetime(df["trading_date"]).dt.strftime("%Y-%m-%d")

    # Drop columns that already exist in df_macro (never overwrite)
    already_present = [
        c for c in available
        if c != "trading_date" and c in df.columns
    ]
    if already_present:
        logger.debug(
            "join_daily_context: skipping %d already-present columns: %s",
            len(already_present), already_present,
        )
        ctx = ctx.drop(columns=already_present)

    df = df.merge(ctx, on="trading_date", how="left")

    # Restore trading_date to datetime64[ns] (pipeline expects this dtype)
    df["trading_date"] = pd.to_datetime(df["trading_date"])

    n_joined = df["gap_direction"].notna().sum() if "gap_direction" in df.columns else -1
    coverage = n_joined / len(df) if len(df) > 0 and n_joined >= 0 else 1.0
    if coverage < 0.95 and n_joined >= 0:
        logger.warning(
            "join_daily_context: %s — low coverage %.1f%% (%d / %d rows unmatched)",
            instrument, coverage * 100, len(df) - n_joined, len(df),
        )
    logger.info(
        "join_daily_context: %s — joined %d / %d rows",
        instrument, n_joined, len(df),
    )

    return df
