import sqlite3
import json
import os

db_path = r"C:\Users\vinay\.cache\codebase-memory-mcp\c-Users-vinay-tvDownloadOHLC.db"
output_path = r"docs\mcp_brainstorming\structural_truth.md"

def generate_map():
    if not os.path.exists(db_path):
        print(f"DB not found: {db_path}")
        return

    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# Repository Structural Truth (Generated via CBM-MCP Graph)\n\n")
        f.write("> [!NOTE]\n")
        f.write("> This document is generated by analyzing the 36,000+ nodes and 54,000+ edges in the Codebase Memory graph.\n")
        f.write("> It represents the *actual* code structure, bypassing outdated manual documentation.\n\n")

        # 1. API Routes
        f.write("## 🌐 API Route Topology\n")
        f.write("The following routes represent the system's entry points. These are high-signal targets for MCP tool exposure.\n\n")
        f.write("| Route | Handler | File |\n")
        f.write("| :--- | :--- | :--- |\n")
        
        cursor.execute("""
            SELECT name, qualified_name, file_path 
            FROM nodes 
            WHERE label = 'Route'
            ORDER BY file_path
        """)
        routes = cursor.fetchall()
        for r in routes:
            f.write(f"| `{r[0]}` | `{r[1]}` | `{r[2]}` |\n")
        
        # 2. Functional Hubs (Most Called Functions)
        f.write("\n## 🚀 Functional Hubs (High-Signal Services)\n")
        f.write("These functions are the most frequently called across the repository, indicating core utility logic.\n\n")
        f.write("| Function | Calls Count | File |\n")
        f.write("| :--- | :--- | :--- |\n")
        
        cursor.execute("""
            SELECT n.name, COUNT(e.id) as call_count, n.file_path
            FROM nodes n
            JOIN edges e ON n.id = e.target_id
            WHERE n.label IN ('Function', 'Method') AND e.type = 'CALLS'
            GROUP BY n.id
            ORDER BY call_count DESC
            LIMIT 15
        """)
        hubs = cursor.fetchall()
        for h in hubs:
            f.write(f"| `{h[0]}` | {h[1]} | `{h[2]}` |\n")

        # 3. Cross-Directory Dependencies
        f.write("\n## 🔗 Cross-Directory Dependencies\n")
        f.write("Analyzing how major directories interact via functional calls.\n\n")
        
        cursor.execute("""
            SELECT 
                CASE WHEN INSTR(n_from.file_path, '/') > 0 
                     THEN SUBSTR(n_from.file_path, 1, INSTR(n_from.file_path, '/') - 1)
                     ELSE 'root' END as from_dir,
                CASE WHEN INSTR(n_to.file_path, '/') > 0 
                     THEN SUBSTR(n_to.file_path, 1, INSTR(n_to.file_path, '/') - 1)
                     ELSE 'root' END as to_dir,
                COUNT(*) as call_count
            FROM edges e
            JOIN nodes n_from ON e.source_id = n_from.id
            JOIN nodes n_to ON e.target_id = n_to.id
            WHERE e.type = 'CALLS'
            GROUP BY from_dir, to_dir
            HAVING from_dir != to_dir
            ORDER BY call_count DESC
        """)
        deps = cursor.fetchall()
        f.write("| From Directory | To Directory | Call Count |\n")
        f.write("| :--- | :--- | :--- |\n")
        for d in deps:
            f.write(f"| `{d[0]}` | `{d[1]}` | {d[2]} |\n")

    conn.close()
    print(f"Structural truth generated at {output_path}")

if __name__ == "__main__":
    generate_map()
