"""
Shared dataclasses for risk management state.
"""
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional
import pandas as pd


class TradeDirection(Enum):
    LONG = "long"
    SHORT = "short"


class TradeStatus(Enum):
    PENDING = "pending"          # Signal generated, not yet entered
    OPEN = "open"                # Position is live
    PARTIAL = "partial"          # Partial exit taken, remainder open
    CLOSED = "closed"            # Fully exited
    VETOED = "vetoed"            # Rejected by risk manager


@dataclass
class Signal:
    """Generated by a strategy's signal module."""
    timestamp: pd.Timestamp
    strategy_name: str
    symbol: str
    direction: TradeDirection
    entry_price: float
    stop_price: float
    risk_points: float           # abs(entry_price - stop_price)
    risk_dollars: float          # risk_points * point_value * contracts
    context: dict                # Strategy-specific metadata (chop_score, regime, etc.)


@dataclass
class TradeRecord:
    """Complete record of a trade, filled in progressively as the trade evolves."""
    signal: Signal
    status: TradeStatus = TradeStatus.PENDING
    entry_time: Optional[pd.Timestamp] = None
    entry_fill_price: Optional[float] = None
    # Partial exit
    partial_exit_time: Optional[pd.Timestamp] = None
    partial_exit_price: Optional[float] = None
    partial_exit_pct: Optional[float] = None
    # Final exit
    exit_time: Optional[pd.Timestamp] = None
    exit_fill_price: Optional[float] = None
    exit_reason: Optional[str] = None  # "stop", "target", "trail", "time_stop", "flatten", "session_risk"
    # P&L
    realized_pnl: float = 0.0
    # Analytics
    mae_points: float = 0.0     # Maximum adverse excursion during trade
    mfe_points: float = 0.0     # Maximum favorable excursion during trade
    bars_in_trade: int = 0
    policy_name: str = ""       # Which trade management policy was used


@dataclass
class SessionState:
    """Tracks session-level risk state. Reset at each session open."""
    trading_date: Optional[pd.Timestamp] = None
    trade_count: int = 0
    consecutive_losers: int = 0
    session_pnl: float = 0.0
    is_paused: bool = False
    pause_until: Optional[pd.Timestamp] = None
    is_stopped_for_day: bool = False
    open_position: Optional[TradeRecord] = None
    trades: list = field(default_factory=list)


@dataclass
class AccountState:
    """Tracks account-level state across sessions."""
    equity: float = 50000.0
    high_water_mark: float = 50000.0   # EOD trailing — updates at session close
    peak_equity: float = 50000.0
    trailing_drawdown_remaining: float = 2000.0
    weekly_pnl: float = 0.0
    weekly_start_equity: float = 50000.0
    is_in_observation: bool = False
    is_blown: bool = False             # Trailing drawdown breached
    days_traded: int = 0
    daily_pnls: list = field(default_factory=list)
