"""
LLM Reviewer & Prompt Generator for CSP Finalists
Extracts multi-quarter financial trajectory, RS line metrics, and generates
the institutional review prompt matching Ben (@PatternProfits)'s methodology.
"""

import json
from datetime import date
from typing import List, Dict, Any, Optional
from pathlib import Path
import yfinance as yf
import pandas as pd

from scripts.csp_ranking.scoring_engine import ScoredCandidate


def extract_multi_quarter_data(ticker: str) -> Dict[str, Any]:
    """
    Pulls last 4 quarters of Revenue and EPS to evaluate trajectory.
    """
    ticker = ticker.upper().strip()
    result = {
        "ticker": ticker,
        "revenue_sequence": [],
        "eps_sequence": [],
        "revenue_growth_yoy": [],
        "is_recent_ipo": False,
        "quarters_available": 0,
    }
    
    try:
        stock = yf.Ticker(ticker)
        q_inc = stock.quarterly_income_stmt
        if q_inc is not None and not q_inc.empty:
            # Revenue
            if "Total Revenue" in q_inc.index:
                rev_row = q_inc.loc["Total Revenue"].dropna()
                # Most recent quarters (up to 5)
                revs = list(rev_row.values[:5])
                rev_dates = [d.strftime("%b '%y") if hasattr(d, "strftime") else str(d) for d in rev_row.index[:5]]
                result["revenue_sequence"] = [
                    {"date": d, "revenue": f"${v/1e6:.1f}M" if v < 1e9 else f"${v/1e9:.2f}B"}
                    for d, v in zip(rev_dates, revs)
                ]
                result["quarters_available"] = len(revs)
                if len(revs) < 6:
                    result["is_recent_ipo"] = True

            # Diluted EPS / Net Income
            if "Diluted EPS" in q_inc.index:
                eps_row = q_inc.loc["Diluted EPS"].dropna()
                eps_vals = list(eps_row.values[:5])
                eps_dates = [d.strftime("%b '%y") if hasattr(d, "strftime") else str(d) for d in eps_row.index[:5]]
                result["eps_sequence"] = [
                    {"date": d, "eps": f"${v:.2f}"}
                    for d, v in zip(eps_dates, eps_vals)
                ]

    except Exception as e:
        print(f"[extract_multi_quarter_data] Note on {ticker}: {e}")

    return result


def generate_llm_csp_review_prompt(
    finalists: List[ScoredCandidate],
    scan_date: Optional[date] = None,
) -> str:
    """
    Generates the master LLM review prompt for Ollama/Cloud models.
    """
    today_str = (scan_date or date.today()).strftime("%b %d, %Y")
    
    candidates_payload = []
    for c in finalists:
        q_data = extract_multi_quarter_data(c.contract.ticker)
        
        # RS Line metrics
        rs_str = "N/A"
        if c.technicals and c.technicals.rs_ratio > 0:
            rs_val = round(c.technicals.rs_ratio * 100, 2)
            rs_ma = round(c.technicals.rs_sma21 * 100, 2)
            status = "ABOVE MA" if c.technicals.is_rs_above_ma else "BELOW MA"
            slope = f"{c.technicals.rs_slope_10d:+.1f}% (10d)"
            rs_str = f"{rs_val} vs {rs_ma} ({status}, 10d slope: {slope})"

        item = {
            "rank": c.rank,
            "ticker": c.contract.ticker,
            "strike": f"${c.contract.strike:.2f}",
            "mark": f"${c.mark:.2f}",
            "expiry": c.contract.expiry_date.strftime("%b %d, %Y") if c.contract.expiry_date else "-",
            "dte": c.contract.dte,
            "delta": round(c.contract.delta, 2),
            "trade_ror": f"{c.trade_ror_pct:.2f}%",
            "annualized_ror": f"{c.contract.annualized_ror_pct:.1f}%",
            "otm_cushion": f"{c.cushion_details.get('otm_cushion_pct', 0.0):.1f}%",
            "base_score": c.base_score,
            "bid_ask_spread": f"${c.contract.bid:.2f} / ${c.contract.ask:.2f} ({c.contract.spread_pct*100:.0f}% spd)",
            "volume": c.contract.volume,
            "earnings_date": c.profile.earnings_date.strftime("%b %d, %Y") if (c.profile and c.profile.earnings_date) else (c.profile.earnings_str if c.profile else "-"),
            "finviz_sales_qq": f"{c.profile.sales_qq:+.1f}%" if c.profile else "N/A",
            "finviz_eps_qq": f"{c.profile.eps_qq:+.1f}%" if c.profile else "N/A",
            "rs_line_data": rs_str,
            "quarterly_revenue_history": q_data["revenue_sequence"],
            "quarterly_eps_history": q_data["eps_sequence"],
            "is_recent_ipo_or_thin_data": q_data["is_recent_ipo"],
        }
        candidates_payload.append(item)

    prompt = f"""# ROLE: Institutional Premium Selling & Cash-Secured Put (CSP) Risk Analyst
You are reviewing a filtered list of Cash-Secured Put (CSP) finalists generated by an automated quantitative scanner (Ben / @PatternProfits methodology).

## TASK OVERVIEW
The mechanical scanner has calculated the Base Score (0-100) based on Return on Risk (25), Spread Tightness (20), Liquidity (15), Technical Cushion (15), Fundamentals (15), and Delta (10).

Your objective is to apply the **Decisive Qualitative & Trend Adjustment Layer** by deeply inspecting:
1. **Relative Strength (RS) Line**: Ratio vs SPY benchmark relative to its 21-day MA and recent momentum slope.
2. **Revenue Trajectory (Last 3-4 Quarters)**: Detecting growth acceleration vs deceleration hiding behind static single-period figures.
3. **EPS Trajectory (Last 3-4 Quarters)**: Consecutive dollar trajectory, turnaround stability, or deceleration.
4. **Contextual Risk Flags**: Recent IPOs, thin trading histories, erratic earnings, or binary sector risks.

---

## SCORING & ADJUSTMENT RUBRIC
Apply these exact point adjustments to the Base Score:
- **RS Line**:
  - `+5 pts`: Cleanly above its 21-day MA (outperforming SPY benchmark)
  - `-5 pts`: Below its 21-day MA or breaking down below moving average
- **Revenue Trend (Last 3-4 Quarters)**:
  - `+5 pts`: Accelerating or consistently strong growth
  - ` 0 pts`: Mixed, choppy, or moderate plateau
  - `-8 pts`: Decelerating growth sequence (e.g. +77% -> +20% -> +7%) or negative revenue
- **EPS Trend (Last 3-4 Quarters)**:
  - `+5 pts`: Accelerating growth, sustained turnaround to profitability, beating expectations
  - ` 0 pts`: Choppy, stable but no clear momentum
  - `-8 pts`: Decelerating EPS dollar amounts, widening losses, or negative surprises

`Adjusted Score = Base Score + RS_Adj + Rev_Adj + EPS_Adj` (clamped between 0 and 100)

---

## INPUT DATA: CANDIDATE FINALISTS ({today_str})

```json
{json.dumps(candidates_payload, indent=2)}
```

---

## REQUIRED OUTPUT FORMAT

Produce your review strictly in the following 3-Section structure:

### 1. Multi-Quarter Trajectory & Relative Strength Read
Generate a clean Markdown table with the following columns:
| Ticker | RS Line Read | Revenue Trend (Last 3-4 Qtrs) | EPS Trend (Last 3-4 Qtrs) | Notes & Risk Flags |
| :--- | :--- | :--- | :--- | :--- |

*(In the Notes column, flag recent IPOs, data limitations, momentum shifts, or stability factors)*.

### 2. Final Adjusted Rankings
Generate the final ranked leaderboard sorted by **Adjusted Score (Descending)**:
| Rank | Ticker | Strike | Mark | Exp | Base Score | RS Adj | Rev Adj | EPS Adj | Final Adj. Score | ROR |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |

### 3. Decisive Trade Commentary & Actionable Tiers
Provide concise, institutional execution guidance:
- **Major Movers**: Highlight any candidate whose rank shifted significantly due to deceleration (e.g., high base score ruined by decelerating growth) or RS momentum shifts.
- **Tier 1: High-Conviction Green Lights**: Clean technical cushion, strong RS line, accelerating growth, solid liquidity.
- **Tier 2: Cautious / Secondary Plays**: Viable but with minor drag (e.g., mixed EPS or choppy revenue).
- **Tier 3: Disqualified / Avoid**: Disqualified due to fundamental deceleration or breakdown despite attractive mechanical yield.
"""
    return prompt
