import { NextRequest, NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';
import fs from 'fs/promises';
import path from 'path';

const prisma = new PrismaClient();

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;

  try {
    // 1. Fetch Run Metadata from DB
    const run = await prisma.researchRun.findUnique({
      where: { id },
      select: { equityCurvePath: true }
    });

    if (!run || !run.equityCurvePath) {
      return NextResponse.json({ error: 'Run not found or curve path missing' }, { status: 404 });
    }

    const curvePath = run.equityCurvePath;

    // 2a. If the stored path is a PNG (legacy options strategies), check for a
    //     sibling .json file generated by the analytics engine. If the JSON
    //     exists, serve that; otherwise return an empty equity payload so the
    //     frontend can render an empty chart instead of crashing.
    if (curvePath.endsWith('.png')) {
      const jsonPath = curvePath.replace(/\.png$/, '.json');
      try {
        const fileContent = await fs.readFile(jsonPath, 'utf-8');
        const data = JSON.parse(fileContent);
        return NextResponse.json(data);
      } catch {
        // No JSON sibling — return empty payload
        return NextResponse.json({ timestamps: [], values: [] });
      }
    }

    // 2b. Normal path: read the JSON equity data file
    const fileContent = await fs.readFile(curvePath, 'utf-8');
    const data = JSON.parse(fileContent);

    return NextResponse.json(data);
  } catch (error) {
    console.error('Error loading equity curve:', error);
    return NextResponse.json({ error: 'Failed to load equity data' }, { status: 500 });
  }
}
