#region Using declarations
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using System.Windows.Media;
using System.Xml.Serialization;
using NinjaTrader.Cbi;
using NinjaTrader.Gui;
using NinjaTrader.Gui.Chart;
using NinjaTrader.Gui.SuperDom;
using NinjaTrader.Gui.Tools;
using NinjaTrader.Data;
using NinjaTrader.NinjaScript;
using NinjaTrader.Core.FloatingPoint;
using NinjaTrader.NinjaScript.DrawingTools;
#endregion

//This namespace holds Indicators in this folder and is required. Do not change it.
namespace NinjaTrader.NinjaScript.Indicators
{
    public class RangeProbabilityIndicator : Indicator
    {
        #region Variables
        private int rangeMinutes = 60;
        private int anchorHourET = 18;
        private bool showBox = true;
        private bool showLevels = true;
        private bool showGrid = true;
        private bool showBand = true;
        private bool showHud = true;
        private double minProbThreshold = 70.0;
        private int minSampleSize = 20;

        private DateTime currentRangeStart = DateTime.MinValue;
        private DateTime priorRangeStart = DateTime.MinValue;
        private double curO = double.NaN;
        private double curH = double.MinValue;
        private double curL = double.MaxValue;
        private double prvH = double.NaN;
        private double prvL = double.NaN;
        private double prvO = double.NaN;
        private double prvC = double.NaN;

        private double openPos = double.NaN;
        private int bucketIdx = -1;
        private string slotStr = "";
        private string sDir = "NONE";
        private double sProb = double.NaN;
        private double sTest = double.NaN;
        private int sN = 0;
        private double sRes = double.NaN;
        private bool isQualified = false;

        // Rolling audit scorecard
        private List<double> liveClaims = new List<double>();
        private List<int> liveWins = new List<int>();
        private List<int> liveResolved = new List<int>();
        private List<double> liveResolveClaims = new List<double>();

        // Lookup table key: Slot (HHMM) + BucketChar (0..b) -> Values (Dir, Prob, Test, N, Res)
        private Dictionary<string, string> lookupTable = new Dictionary<string, string>();
        private TimeZoneInfo nyTimeZone;
        #endregion

        protected override void OnStateChange()
        {
            if (State == State.SetDefaults)
            {
                Description = @"Range Probability Empirical Transition & Decile Expansion Engine for NinjaTrader 8.";
                Name = "RangeProbabilityIndicator";
                Calculate = Calculate.OnBarClose;
                IsOverlay = true;
                DisplayInDataBox = true;
                DrawOnPricePanel = true;
                PaintPriceMarkers = true;
                IsSuspendedWhileInactive = true;

                RangeMinutes = 60;
                AnchorHourET = 18;
                ShowBox = true;
                ShowLevels = true;
                ShowGrid = false;
                ShowBand = true;
                ShowHud = true;
                MinProbThreshold = 70.0;
                MinSampleSize = 20;

                AddPlot(new Stroke(Brushes.DodgerBlue, 2), PlotStyle.Line, "PriorHigh");
                AddPlot(new Stroke(Brushes.Gray, DashStyleHelper.Dash, 1), PlotStyle.Line, "PriorMid");
                AddPlot(new Stroke(Brushes.Crimson, 2), PlotStyle.Line, "PriorLow");
            }
            else if (State == State.Configure)
            {
                try
                {
                    nyTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");
                }
                catch
                {
                    nyTimeZone = TimeZoneInfo.Local;
                }
                InitializeLookupTable();
            }
        }

        private void InitializeLookupTable()
        {
            lookupTable.Clear();
            // Load LUT entries from the generated data class.
            // The RangeProbabilityLutData class is auto-generated by
            // scripts/range_probability/build_ninjatrader_lut.py and contains
            // the 17-char encoded records for each (slot, bucket) cell.
            var entries = RangeProbabilityLutData.GetEntries();
            foreach (var entry in entries)
            {
                // entry.Key = slot(4) + bucketChar(1), entry.Value = dir(1) + prob(3) + test(3) + N(3) + res(2)
                if (!lookupTable.ContainsKey(entry.Key))
                    lookupTable[entry.Key] = entry.Value;
            }
        }

        protected override void OnBarUpdate()
        {
            if (CurrentBar < 5) return;

            DateTime timeNy = TimeZoneInfo.ConvertTime(Time[0], nyTimeZone);
            int etMins = timeNy.Hour * 60 + timeNy.Minute;
            int sinceAnchor = (etMins - anchorHourET * 60 + 1440) % 1440;
            int rIdx = sinceAnchor / rangeMinutes;
            int offsetMins = sinceAnchor % rangeMinutes;
            DateTime rStart = timeNy.AddMinutes(-offsetMins).AddSeconds(-timeNy.Second);

            bool isNewRange = (currentRangeStart == DateTime.MinValue) || (rStart != currentRangeStart);

            if (isNewRange)
            {
                // Score the range that just closed
                if (!double.IsNaN(curO) && !double.IsNaN(prvH) && prvH > prvL)
                {
                    double prevClose = Close[1];
                    bool wasUp = prevClose > prvH;
                    bool wasDn = prevClose < prvL;
                    bool wasRes = wasUp || wasDn;

                    if (isQualified && !double.IsNaN(sProb))
                    {
                        liveClaims.Add(sProb);
                        liveResolveClaims.Add(sRes);
                        liveResolved.Add(wasRes ? 1 : 0);
                        if (wasRes)
                        {
                            bool won = (sDir == "U" && wasUp) || (sDir == "D" && wasDn);
                            liveWins.Add(won ? 1 : 0);
                        }
                    }

                    // Draw completed box
                    if (ShowBox)
                    {
                        string boxTag = "RangeBox_" + currentRangeStart.Ticks;
                        Brush boxBrush = wasUp ? Brushes.Teal : wasDn ? Brushes.Maroon : Brushes.DimGray;
                        Draw.Rectangle(this, boxTag, false, 0, curH, 1, curL, Brushes.Transparent, boxBrush, 30);
                    }
                }

                // Roll forward
                if (!double.IsNaN(curO))
                {
                    prvH = curH;
                    prvL = curL;
                    prvO = curO;
                    prvC = Close[1];
                    priorRangeStart = currentRangeStart;
                }

                currentRangeStart = rStart;
                curO = Open[0];
                curH = High[0];
                curL = Low[0];

                slotStr = rStart.ToString("HHmm");
                isQualified = false;
                sProb = double.NaN;
                sDir = "NONE";

                // Evaluate Opening Decile
                if (!double.IsNaN(prvH) && prvH > prvL)
                {
                    double span = prvH - prvL;
                    openPos = (curO - prvL) / span;

                    if (openPos < 0.0) bucketIdx = 0;
                    else if (openPos >= 1.0) bucketIdx = 11;
                    else bucketIdx = Math.Min(10, Math.Max(1, (int)Math.Floor(openPos * 10) + 1));

                    string bChar = "0123456789ab".Substring(bucketIdx, 1);
                    string key = slotStr + bChar;

                    if (lookupTable.ContainsKey(key))
                    {
                        string v = lookupTable[key];
                        sDir = v.Substring(0, 1);
                        sProb = double.Parse(v.Substring(1, 3));
                        sTest = double.Parse(v.Substring(4, 3));
                        sN = int.Parse(v.Substring(7, 3));
                        sRes = double.Parse(v.Substring(10, 2));
                        isQualified = (sProb >= minProbThreshold) && (sN >= minSampleSize);
                    }
                    else
                    {
                        // No LUT entry for this (slot, bucket) cell.
                        // Do NOT fabricate a heuristic signal -- the indicator
                        // only fires on empirically validated edges.
                        sDir = "NONE";
                        sProb = double.NaN;
                        sTest = double.NaN;
                        sN = 0;
                        sRes = double.NaN;
                        isQualified = false;
                    }

                    // Place signal marker
                    if (isQualified)
                    {
                        string markerTag = "Sig_" + currentRangeStart.Ticks;
                        if (sDir == "U")
                            Draw.ArrowUp(this, markerTag, false, 0, Low[0] - 2 * TickSize, Brushes.Teal);
                        else
                            Draw.ArrowDown(this, markerTag, false, 0, High[0] + 2 * TickSize, Brushes.Maroon);
                    }
                }
            }
            else
            {
                curH = Math.Max(curH, High[0]);
                curL = Math.Min(curL, Low[0]);
            }

            // Assign Plot Values
            if (!double.IsNaN(prvH) && prvH > prvL && ShowLevels)
            {
                PriorHigh[0] = prvH;
                PriorMid[0] = (prvH + prvL) / 2.0;
                PriorLow[0] = prvL;
            }

            // Render on-chart HUD text box
            if (ShowHud)
            {
                RenderHudTable();
            }
        }

        private void RenderHudTable()
        {
            double liveWinRate = liveWins.Count > 0 ? (liveWins.Sum() / (double)liveWins.Count * 100.0) : 0.0;
            double claimAvg = liveClaims.Count > 0 ? liveClaims.Average() : 0.0;
            double drift = liveWinRate - claimAvg;

            StringBuilder sb = new StringBuilder();
            sb.AppendLine($"=== RANGE PROBABILITY ({RangeMinutes}M) ===");
            sb.AppendLine($"Slot: {slotStr} ET | Open Pos: {openPos:F2} (Bucket {bucketIdx})");
            if (isQualified)
            {
                sb.AppendLine($"Direction: Closes {(sDir == "U" ? "ABOVE HIGH" : "BELOW LOW")}");
                sb.AppendLine($"Probability: {sProb:F0}% (Resolve Rate: {sRes:F0}%) | Sample: {sN}");
            }
            else
            {
                sb.AppendLine("Direction: No >= 70% Edge");
            }
            sb.AppendLine("--------------------------------");
            sb.AppendLine($"Live Track ({liveWins.Count} calls): Actual {liveWinRate:F0}% vs Claim {claimAvg:F0}%");
            sb.AppendLine($"Drift: {(drift >= 0 ? "+" : "")}{drift:F1} pts");

            Draw.TextFixed(this, "RangeProbHUD", sb.ToString(), TextPosition.TopRight, Brushes.White, new SimpleFont("Arial", 11), Brushes.DimGray, Brushes.Black, 85);
        }

        #region Properties
        [NinjaScriptProperty]
        [Range(15, 240)]
        [Display(Name = "Range Minutes", GroupName = "Parameters", Order = 1)]
        public int RangeMinutes { get => rangeMinutes; set => rangeMinutes = value; }

        [NinjaScriptProperty]
        [Range(0, 23)]
        [Display(Name = "Anchor Hour (ET)", GroupName = "Parameters", Order = 2)]
        public int AnchorHourET { get => anchorHourET; set => anchorHourET = value; }

        [NinjaScriptProperty]
        [Display(Name = "Draw Range Boxes", GroupName = "Visuals", Order = 3)]
        public bool ShowBox { get => showBox; set => showBox = value; }

        [NinjaScriptProperty]
        [Display(Name = "Show Prior High/Mid/Low", GroupName = "Visuals", Order = 4)]
        public bool ShowLevels { get => showLevels; set => showLevels = value; }

        [NinjaScriptProperty]
        [Display(Name = "Show HUD Statistics Table", GroupName = "Visuals", Order = 5)]
        public bool ShowHud { get => showHud; set => showHud = value; }

        [NinjaScriptProperty]
        [Range(50.0, 95.0)]
        [Display(Name = "Min Probability Edge (%)", GroupName = "Filters", Order = 6)]
        public double MinProbThreshold { get => minProbThreshold; set => minProbThreshold = value; }

        [NinjaScriptProperty]
        [Range(10, 500)]
        [Display(Name = "Min Sample Size", GroupName = "Filters", Order = 7)]
        public int MinSampleSize { get => minSampleSize; set => minSampleSize = value; }

        [Browsable(false)]
        [XmlIgnore]
        public Series<double> PriorHigh => Values[0];

        [Browsable(false)]
        [XmlIgnore]
        public Series<double> PriorMid => Values[1];

        [Browsable(false)]
        [XmlIgnore]
        public Series<double> PriorLow => Values[2];

        // Signal properties for strategy consumption
        [Browsable(false)]
        [XmlIgnore]
        public string SignalDirection => sDir;

        [Browsable(false)]
        [XmlIgnore]
        public double SignalProbability => sProb;

        [Browsable(false)]
        [XmlIgnore]
        public double SignalResolveRate => sRes;

        [Browsable(false)]
        [XmlIgnore]
        public int SignalSampleSize => sN;

        [Browsable(false)]
        [XmlIgnore]
        public bool SignalIsQualified => isQualified;

        [Browsable(false)]
        [XmlIgnore]
        public int CurrentBucket => bucketIdx;

        [Browsable(false)]
        [XmlIgnore]
        public double CurrentOpenPos => openPos;
        #endregion
    }
}

#region NinjaScript Placement
namespace NinjaTrader.NinjaScript.Indicators
{
    public partial class Indicator : NinjaTrader.Gui.NinjaScript.IndicatorRenderBase
    {
        private RangeProbabilityIndicator[] cacheRangeProbabilityIndicator;
        public RangeProbabilityIndicator RangeProbabilityIndicator(int rangeMinutes, int anchorHourET)
        {
            return RangeProbabilityIndicator(Input, rangeMinutes, anchorHourET);
        }

        public RangeProbabilityIndicator RangeProbabilityIndicator(ISeries<double> input, int rangeMinutes, int anchorHourET)
        {
            if (cacheRangeProbabilityIndicator != null)
                for (int idx = 0; idx < cacheRangeProbabilityIndicator.Length; idx++)
                    if (cacheRangeProbabilityIndicator[idx] != null && cacheRangeProbabilityIndicator[idx].RangeMinutes == rangeMinutes && cacheRangeProbabilityIndicator[idx].AnchorHourET == anchorHourET && cacheRangeProbabilityIndicator[idx].EqualsInput(input))
                        return cacheRangeProbabilityIndicator[idx];
            return new RangeProbabilityIndicator() { RangeMinutes = rangeMinutes, AnchorHourET = anchorHourET };
        }
    }
}
#endregion
