// Auto-generated by scripts/range_probability/build_ninjatrader_lut.py
// DO NOT EDIT MANUALLY -- re-run the builder after updating probability matrices.
using System.Collections.Generic;

namespace NinjaTrader.NinjaScript.Indicators
{
    public static class RangeProbabilityLutData
    {
        // Each entry: key = slot(4) + bucketChar(1), value = dir(1) + prob(3) + test(3) + N(3) + res(2)
        public static Dictionary<string, string> GetEntries()
        {
            var lut = new Dictionary<string, string>();
            // PLACEHOLDER -- populated by build_ninjatrader_lut.py
            // Example: lut["10009"] = "U08408210748";
            return lut;
        }
    }
}