"""
Universal Pine Script Builder
Reads all generated ticker LUT constants from data/range_prob/pine_lut/
and creates a unified, multi-ticker TradingView Pine Script v6 indicator.
"""

import os
import sys

def generate_universal_pine():
    lut_dir = "data/range_prob/pine_lut"
    out_dir = "scripts/indicators-pine/range_probability"
    os.makedirs(out_dir, exist_ok=True)
    out_file = os.path.join(out_dir, "RangeProbability_Universal.pine")

    tickers = ["NQ", "ES", "YM", "RTY", "CL", "GC", "SPY", "QQQ", "AAPL", "NVDA", "TSLA"]
    available_tickers = []

    ticker_code_blocks = {}
    for t in tickers:
        p_path = os.path.join(lut_dir, f"{t}_lut.pine")
        if os.path.exists(p_path):
            available_tickers.append(t)
            with open(p_path, "r", encoding="utf-8") as f:
                content = f.read()
            ticker_code_blocks[t] = content

    print(f"Compiling Universal Pine Script with {len(available_tickers)} assets: {available_tickers}...")

    pine_lines = [
        "// Range Probability  -  Universal Multi-Asset Engine",
        "// Generated by Antigravity Range Probability Engine",
        "//@version=6",
        'indicator("Range Probability  -  Universal", overlay = true, max_boxes_count = 500, max_labels_count = 500)',
        "",
        "// ---------------------------------------------------------------- inputs ----",
        'g0 = "Asset Selection"',
        f'assetSel = input.string("Auto", "Lookup Matrix Asset", options = {["Auto"] + available_tickers}, group = g0, tooltip = "Choose Auto to detect from chart symbol, or select a specific asset matrix.")',
        "",
        'g1 = "Range"',
        'tfSel   = input.string("60", "Range size (minutes)", options = ["15", "30", "60", "120", "240"], group = g1)',
        'anchorH = input.int(18, "Session anchor hour (ET)", minval = 0, maxval = 23, group = g1, tooltip = "Ranges are measured from this hour in New York time. 18:00 matches standard futures session open.")',
        'keepN   = input.int(20, "Ranges to keep on chart", minval = 1, maxval = 400, group = g1)',
        "",
        'g2 = "Box"',
        'showBox  = input.bool(true,  "Draw range boxes", group = g2)',
        'colLive  = input.color(color.new(#787b86, 75), "Forming", group = g2)',
        'colUp    = input.color(color.new(#26a69a, 80), "Closed above previous high", group = g2)',
        'colDn    = input.color(color.new(#ef5350, 80), "Closed below previous low", group = g2)',
        'colIn    = input.color(color.new(#787b86, 90), "Closed inside", group = g2)',
        "",
        'g5 = "Levels"',
        'showHML   = input.bool(true,  "High / mid / low lines from the previous range", group = g5)',
        'extendN   = input.int(0, "Extend them this many ranges ahead", minval = 0, maxval = 50, group = g5)',
        'showHMLlb = input.bool(true,  "Label them", group = g5)',
        'showPrev  = input.bool(true,  "Outline the previous range", group = g5)',
        'showGrid  = input.bool(false, "Open-position levels (0.0 - 1.0)", group = g5)',
        'showBand  = input.bool(true,  "Shade the bucket the range opened in", group = g5)',
        'colHML    = input.color(#4a4d55, "High / low colour", group = g5)',
        'colMidL   = input.color(color.new(#787b86, 25), "Mid colour", group = g5)',
        'colHMLlb  = input.color(color.new(#787b86, 20), "Label colour", group = g5)',
        'wHL       = input.int(1, "High / low thickness", minval = 1, maxval = 5, group = g5)',
        'wMid      = input.int(1, "Mid thickness", minval = 1, maxval = 5, group = g5)',
        'wGrid     = input.int(1, "Open-position level thickness", minval = 1, maxval = 5, group = g5)',
        'colGrid   = input.color(color.new(#787b86, 65), "Open-position level colour", group = g5)',
        'colBand   = input.color(color.new(#787b86, 88), "Bucket shading", group = g5)',
        "",
        'g3 = "Table"',
        'showTbl    = input.bool(true, "Show table", group = g3)',
        'tblPos     = input.string("Top right", "Position", options = ["Top right", "Top left", "Bottom right", "Bottom left", "Middle right"], group = g3)',
        'tblSize    = input.string("Small", "Text size", options = ["Tiny", "Small", "Normal", "Large"], group = g3)',
        'showDetail = input.bool(true, "Show test outcome and sample size", group = g3)',
        "",
        'g4 = "Signals"',
        'showMarker = input.bool(true,  "Label the chart when a cell qualifies", group = g4)',
        'useAlerts  = input.bool(false, "Fire an alert when a cell qualifies", group = g4)',
        'showOthers = input.bool(true,  "Scan the other range sizes for live signals", group = g4)',
        "",
        'g6 = "Live tracker"',
        'showLive = input.bool(true, "Track how the calls are doing on this chart", group = g6)',
        'trackN   = input.int(100, "Calls to keep in the window", minval = 10, maxval = 1000, group = g6)',
        'showDebug  = input.bool(false, "Show lookup diagnostics in the table", group = g4)',
        "",
        "// ------------------------------------------------------------ active asset detection ---",
        "currTicker = syminfo.ticker",
        "detectAsset() =>",
        '    str.contains(currTicker, "NQ") or str.contains(currTicker, "MNQ") or str.contains(currTicker, "USTEC") ? "NQ" :',
        '     str.contains(currTicker, "ES") or str.contains(currTicker, "MES") or str.contains(currTicker, "SPX") or str.contains(currTicker, "US500") ? "ES" :',
        '     str.contains(currTicker, "YM") or str.contains(currTicker, "MYM") or str.contains(currTicker, "US30") ? "YM" :',
        '     str.contains(currTicker, "RTY") or str.contains(currTicker, "M2K") or str.contains(currTicker, "US2000") ? "RTY" :',
        '     str.contains(currTicker, "CL") or str.contains(currTicker, "MCL") or str.contains(currTicker, "OIL") ? "CL" :',
        '     str.contains(currTicker, "GC") or str.contains(currTicker, "MGC") or str.contains(currTicker, "GOLD") ? "GC" :',
        '     str.contains(currTicker, "SPY") ? "SPY" :',
        '     str.contains(currTicker, "QQQ") ? "QQQ" :',
        '     str.contains(currTicker, "AAPL") ? "AAPL" :',
        '     str.contains(currTicker, "NVDA") ? "NVDA" :',
        '     str.contains(currTicker, "TSLA") ? "TSLA" : "NQ"',
        "",
        'activeAsset = assetSel == "Auto" ? detectAsset() : assetSel',
        "",
        "// ------------------------------------------------------------ ticker lookup datasets ---",
    ]

    for t in available_tickers:
        raw_code = ticker_code_blocks[t]
        pine_lines.append(f"// === {t} Lookup Matrices ===")
        lines_t = raw_code.split("\n")
        for l in lines_t:
            if l.startswith("D15 ="):
                pine_lines.append(l.replace("D15 =", f"D15_{t} ="))
            elif l.startswith("D30 ="):
                pine_lines.append(l.replace("D30 =", f"D30_{t} ="))
            elif l.startswith("D60 ="):
                pine_lines.append(l.replace("D60 =", f"D60_{t} ="))
            elif l.startswith("D120 ="):
                pine_lines.append(l.replace("D120 =", f"D120_{t} ="))
            elif l.startswith("D240 ="):
                pine_lines.append(l.replace("D240 =", f"D240_{t} ="))
            elif l.startswith("//") or l.startswith("  + ") or l.strip() == "":
                pine_lines.append(l)

    pine_lines.append("")
    pine_lines.append("// Select active dataset based on activeAsset")
    pine_lines.append("getDatasets(string asset) =>")
    for i, t in enumerate(available_tickers):
        prefix = "    " if i == 0 else "     "
        pine_lines.append(f'{prefix}asset == "{t}" ? array.from(D15_{t}, D30_{t}, D60_{t}, D120_{t}, D240_{t}) :')
    pine_lines.append(f'     array.from(D15_NQ, D30_NQ, D60_NQ, D120_NQ, D240_NQ)')

    pine_lines.append("")
    pine_lines.append("// Populate LUT map")
    pine_lines.append("var map<string, string> LUT = map.new<string, string>()")
    pine_lines.append("if barstate.isfirst")
    pine_lines.append("    activeDatasets = getDatasets(activeAsset)")
    pine_lines.append("    for ti = 0 to 4")
    pine_lines.append("        D = activeDatasets.get(ti)")
    pine_lines.append("        if str.length(D) >= 17")
    pine_lines.append("            for i = 0 to math.floor(str.length(D) / 17) - 1")
    pine_lines.append("                rec = str.substring(D, i * 17, i * 17 + 17)")
    pine_lines.append("                LUT.put(str.tostring(ti) + str.substring(rec, 0, 5), str.substring(rec, 5))")

    pine_lines.append("""
// ------------------------------------------------------------ range clock ---
tfIdx = tfSel == "15" ? 0 : tfSel == "30" ? 1 : tfSel == "60" ? 2 : tfSel == "120" ? 3 : 4
tfM  = math.round(str.tonumber(tfSel))
tfMs = tfM * 60000

etMins      = hour(time, "America/New_York") * 60 + minute(time, "America/New_York")
sinceAnchor = (etMins - anchorH * 60 + 1440) % 1440
rIdx        = math.floor(sinceAnchor / tfM)
rStart      = time - (sinceAnchor % tfM) * 60000
newRange    = ta.change(rIdx) != 0 or barstate.isfirst

// ------------------------------------------------------------ range state ---
var float curO = na
var float curH = na
var float curL = na
var int   curStart = na
var float prvH = na
var float prvL = na
var int   prvStart = na
var box   bx = na
var array<box> boxes = array.new<box>()
var box   prevBx = na
var box   bandBx = na
var array<line> grid = array.new<line>()
var line   lnHi = na
var line   lnMid = na
var line   lnLo = na
var label  lbHi = na
var label  lbMid = na
var label  lbLo = na
var string sKey = ""

// rolling window of calls this chart has actually made
var array<float> tClaim  = array.new_float()
var array<float> tOK     = array.new_float()
var array<float> tResOK  = array.new_float()
var array<float> tResCl  = array.new_float()

var string sSlot   = ""
var float  sOP     = na
var string sBucket = ""
var string sDir    = ""
var float  sProb   = na
var float  sTest   = na
var int    sN      = 0
var float  sRes    = na
var bool   sHit    = false
var bool   sAdj    = false

pad2(int v) =>
    (v < 10 ? "0" : "") + str.tostring(v)

bChar(int i) =>
    str.substring("0123456789ab", i, i + 1)

bName(int i) =>
    i == 0  ? "below prev low" :
     i == 11 ? "at/above prev high" :
     str.tostring((i - 1) / 10.0, "0.0") + " - " + str.tostring(i / 10.0, "0.0")

if newRange
    pc = close[1]
    wasUp  = not na(curO) and not na(prvH) and pc > prvH
    wasDn  = not na(curO) and not na(prvL) and pc < prvL
    wasRes = wasUp or wasDn

    if showLive and sHit and not na(curO)
        tResOK.push(wasRes ? 1 : 0)
        tResCl.push(sRes)
        tClaim.push(sProb)
        tOK.push(not wasRes ? na : (sDir == "U" ? wasUp : wasDn) ? 1 : 0)
        while tClaim.size() > trackN
            tClaim.shift()
            tOK.shift()
            tResOK.shift()
            tResCl.shift()

    if showBox and not na(bx)
        box.set_bgcolor(bx, wasUp ? colUp : wasDn ? colDn : colIn)

    if not na(curO)
        prvH := curH
        prvL := curL
        prvStart := curStart

    curO := open
    curH := high
    curL := low
    curStart := rStart

    sHit := false
    sProb := na
    sTest := na
    sN := 0
    sRes := na
    sOP := na
    sBucket := ""
    sDir := ""
    sAdj := not na(prvStart) and (curStart - prvStart) == tfMs
    sSlot := pad2(hour(curStart, "America/New_York")) + pad2(minute(curStart, "America/New_York"))

    if sAdj and not na(prvH) and prvH > prvL
        sOP := (curO - prvL) / (prvH - prvL)
        bi = sOP < 0 ? 0 : sOP >= 1.0 ? 11 : math.min(10, math.floor(sOP * 10) + 1)
        sBucket := bName(bi)
        sKey := str.tostring(tfIdx) + sSlot + bChar(bi)
        if LUT.contains(sKey)
            v = LUT.get(sKey)
            sDir  := str.substring(v, 0, 1)
            sProb := str.tonumber(str.substring(v, 1, 4))
            sTest := str.tonumber(str.substring(v, 4, 7))
            sN    := math.round(str.tonumber(str.substring(v, 7, 10)))
            sRes  := str.tonumber(str.substring(v, 10, 12))
            sHit  := true

    if showBox
        bx := box.new(curStart, curH, curStart + tfMs, curL, xloc = xloc.bar_time,
             bgcolor = colLive, border_color = color.new(color.gray, 55), border_width = 1)
        boxes.push(bx)
        while boxes.size() > keepN
            box.delete(boxes.shift())

    if sHit and showMarker
        label.new(bar_index, sDir == "U" ? low : high,
             (sDir == "U" ? "▲ " : "▼ ") + str.tostring(sProb, "#") + "%",
             style = sDir == "U" ? label.style_label_up : label.style_label_down,
             color = color.new(sDir == "U" ? color.teal : color.maroon, 20),
             textcolor = color.white, size = size.tiny)

    if sHit and useAlerts and barstate.isconfirmed
        alert(activeAsset + " " + tfSel + "M " + str.substring(sSlot, 0, 2) + ":" + str.substring(sSlot, 2, 4) +
             " ET opened at " + str.tostring(sOP, "0.00") + " " +
             (sDir == "U" ? "closes ABOVE high " : "closes BELOW low ") +
             str.tostring(sProb, "#") + "% (" + str.tostring(sRes, "#") + "% res)", alert.freq_once_per_bar_close)
else
    curH := math.max(curH, high)
    curL := math.min(curL, low)

if showBox and not na(bx) and not na(curStart)
    box.set_top(bx, curH)
    box.set_bottom(bx, curL)
    box.set_right(bx, math.min(curStart + tfMs, time + timeframe.in_seconds() * 1000))

// -------------------------------------------- parallel range scanner ---
TFLIST = array.from(15, 30, 60, 120, 240)
TFNAME = array.from("15M", "30M", "60M", "120M", "240M")

var array<float>  kPH = array.new_float(5, na)
var array<float>  kPL = array.new_float(5, na)
var array<float>  kCH = array.new_float(5, na)
var array<float>  kCL = array.new_float(5, na)
var array<float>  kCO = array.new_float(5, na)
var array<int>    kCS = array.new_int(5, na)
var array<int>    kPS = array.new_int(5, na)
var array<int>    kIX = array.new_int(5, -999)
var array<float>  kPr = array.new_float(5, na)
var array<float>  kRs = array.new_float(5, na)
var array<string> kDr = array.new_string(5, "")

if showOthers
    for i = 0 to 4
        tfi  = TFLIST.get(i)
        tfiMs = tfi * 60000
        idx  = math.floor(sinceAnchor / tfi)
        st   = time - (sinceAnchor % tfi) * 60000
        if idx != kIX.get(i)
            if not na(kCO.get(i))
                kPH.set(i, kCH.get(i))
                kPL.set(i, kCL.get(i))
                kPS.set(i, kCS.get(i))
            kCO.set(i, open)
            kCH.set(i, high)
            kCL.set(i, low)
            kCS.set(i, st)
            kIX.set(i, idx)
            kPr.set(i, na)
            kRs.set(i, na)
            kDr.set(i, "")
            ph = kPH.get(i)
            pl = kPL.get(i)
            ps = kPS.get(i)
            if not na(ph) and not na(ps) and ph > pl and (st - ps) == tfiMs
                o  = (open - pl) / (ph - pl)
                bb = o < 0 ? 0 : o >= 1.0 ? 11 : math.min(10, math.floor(o * 10) + 1)
                kk = str.tostring(i) + pad2(hour(st, "America/New_York")) +
                     pad2(minute(st, "America/New_York")) + bChar(bb)
                if LUT.contains(kk)
                    vv = LUT.get(kk)
                    kDr.set(i, str.substring(vv, 0, 1))
                    kPr.set(i, str.tonumber(str.substring(vv, 1, 4)))
                    kRs.set(i, str.tonumber(str.substring(vv, 10, 12)))
        else
            kCH.set(i, math.max(kCH.get(i), high))
            kCL.set(i, math.min(kCL.get(i), low))

// ------------------------------------------------------- visual levels & grid -----
if barstate.isfirst
    for i = 0 to 10
        grid.push(line.new(na, na, na, na, xloc = xloc.bar_time, extend = extend.none))
    lnHi  := line.new(na, na, na, na, xloc = xloc.bar_time, width = 2)
    lnMid := line.new(na, na, na, na, xloc = xloc.bar_time, width = 1, style = line.style_dashed)
    lnLo  := line.new(na, na, na, na, xloc = xloc.bar_time, width = 2)
    lbHi  := label.new(na, na, "", xloc = xloc.bar_time, style = label.style_none, size = size.small)
    lbMid := label.new(na, na, "", xloc = xloc.bar_time, style = label.style_none, size = size.small)
    lbLo  := label.new(na, na, "", xloc = xloc.bar_time, style = label.style_none, size = size.small)

if newRange and not na(prvH) and not na(prvStart) and prvH > prvL
    xL = prvStart
    xR = curStart + tfMs
    rng = prvH - prvL

    if showPrev
        if na(prevBx)
            prevBx := box.new(xL, prvH, prvStart + tfMs, prvL, xloc = xloc.bar_time,
                 bgcolor = color.new(color.gray, 100), border_color = colGrid,
                 border_width = 2, border_style = line.style_solid)
        else
            box.set_lefttop(prevBx, xL, prvH)
            box.set_rightbottom(prevBx, prvStart + tfMs, prvL)

    xEnd = curStart + tfMs * (1 + extendN)
    for [k, ln] in array.from(lnHi, lnMid, lnLo)
        y = k == 0 ? prvH : k == 1 ? (prvH + prvL) / 2 : prvL
        line.set_xy1(ln, xL, y)
        line.set_xy2(ln, xEnd, y)
        line.set_extend(ln, extend.none)
        line.set_color(ln, not showHML ? color.new(color.gray, 100) : k == 1 ? colMidL : colHML)
        line.set_width(ln, k == 1 ? wMid : wHL)
    if showHMLlb
        for [k, lb] in array.from(lbHi, lbMid, lbLo)
            y = k == 0 ? prvH : k == 1 ? (prvH + prvL) / 2 : prvL
            label.set_xy(lb, xEnd, y)
            label.set_text(lb, not showHML ? "" :
                 activeAsset + " " + tfSel + (k == 0 ? " HIGH" : k == 1 ? " MID" : " LOW"))
            label.set_textcolor(lb, colHMLlb)
            label.set_style(lb, label.style_label_left)
            label.set_color(lb, color.new(color.gray, 100))

    for i = 0 to 10
        ln = grid.get(i)
        y = prvL + rng * i / 10.0
        edge = i == 0 or i == 10
        line.set_xy1(ln, xL, y)
        line.set_xy2(ln, xR, y)
        line.set_color(ln, showGrid or edge ? colGrid : color.new(color.gray, 100))
        line.set_width(ln, wGrid)
        line.set_style(ln, edge ? line.style_solid : i == 5 ? line.style_dashed : line.style_dotted)

    if showBand and not na(sOP) and sOP >= 0 and sOP < 1.0
        k = math.floor(sOP * 10)
        yb = prvL + rng * k / 10.0
        yt = prvL + rng * (k + 1) / 10.0
        if na(bandBx)
            bandBx := box.new(curStart, yt, xR, yb, xloc = xloc.bar_time,
                 bgcolor = colBand, border_color = color.new(color.gray, 100))
        else
            box.set_lefttop(bandBx, curStart, yt)
            box.set_rightbottom(bandBx, xR, yb)
    else if not na(bandBx)
        box.set_lefttop(bandBx, curStart, prvL)
        box.set_rightbottom(bandBx, curStart, prvL)

// ---------------------------------------------------------------- table -----
posOf(string s) =>
    s == "Top left"      ? position.top_left :
     s == "Bottom right" ? position.bottom_right :
     s == "Bottom left"  ? position.bottom_left :
     s == "Middle right" ? position.middle_right : position.top_right

sizeOf(string s) =>
    s == "Tiny" ? size.tiny : s == "Normal" ? size.normal : s == "Large" ? size.large : size.small

pc(float v) =>
    na(v) ? "—" : str.tostring(v, "0.#") + "%"

pc2(float v) =>
    na(v) ? "—" : str.tostring(v, "0") + "%"

var table tb = table.new(posOf(tblPos), 2, 22, border_width = 1,
     frame_color = color.new(color.gray, 55), frame_width = 1,
     border_color = color.new(color.gray, 85))

if showTbl and barstate.islast
    ts  = sizeOf(tblSize)
    tx  = chart.fg_color
    dim = color.new(chart.fg_color, 45)
    hdr = color.new(color.gray, 88)
    sec = color.new(color.gray, 92)
    tooHigh = timeframe.in_seconds() > tfM * 60
    sigCol  = not sHit ? dim : sDir == "U" ? color.teal : color.maroon
    upCol   = sHit and sDir == "U" ? color.teal : dim
    dnCol   = sHit and sDir == "D" ? color.maroon : dim

    pUpCond = na(sProb) ? na : sDir == "U" ? sProb : 100 - sProb
    uAbove  = na(sRes)  ? na : pUpCond * sRes / 100.0
    uBelow  = na(sRes)  ? na : (100 - pUpCond) * sRes / 100.0
    uInside = na(sRes)  ? na : 100 - sRes

    dirTxt = not sAdj ? "no adjacent previous range" :
              sHit    ? (sDir == "U" ? "closes ABOVE previous high" : "closes BELOW previous low") :
              "nothing at or above 70%"
    foot = showDebug ? "Asset: " + activeAsset + " | Cells: " + str.tostring(LUT.size()) :
             tooHigh  ? "chart timeframe is above range size" :
             "range close only — wicks do not count"
    detL = showDetail ? "train / test  ·  sample" : ""
    detR = not showDetail ? "" : sHit ? str.tostring(sProb, "0") + " / " +
             str.tostring(sTest, "0") + "  ·  " + str.tostring(sN) : "—"

    table.cell(tb, 0, 0, activeAsset + " · " + tfSel + "M", text_color = tx, text_size = ts, bgcolor = hdr, text_halign = text.align_left)
    table.cell(tb, 1, 0, sSlot == "" ? "" : str.substring(sSlot, 0, 2) + ":" + str.substring(sSlot, 2, 4) + " ET", text_color = tx, text_size = ts, bgcolor = hdr, text_halign = text.align_right)

    table.cell(tb, 0, 1, "opened at", text_color = dim, text_size = ts, text_halign = text.align_left)
    table.cell(tb, 1, 1, na(sOP) ? "—" : str.tostring(sOP, "0.00"), text_color = tx, text_size = ts, text_halign = text.align_right)

    table.cell(tb, 0, 2, "bucket", text_color = dim, text_size = ts, text_halign = text.align_left)
    table.cell(tb, 1, 2, sBucket == "" ? "—" : sBucket, text_color = tx, text_size = ts, text_halign = text.align_right)

    table.cell(tb, 0, 3, "IF IT CLOSES OUTSIDE PREV RANGE", text_color = dim, text_size = ts, bgcolor = sec, text_halign = text.align_left)
    table.cell(tb, 1, 3, "", text_size = ts, bgcolor = sec)

    table.cell(tb, 0, 4, dirTxt, text_color = sigCol, text_size = ts, text_halign = text.align_left)
    table.cell(tb, 1, 4, sHit ? pc(sProb) : "—", text_color = sigCol, text_size = ts, text_halign = text.align_right)

    table.cell(tb, 0, 5, "…and it closes outside", text_color = dim, text_size = ts, text_halign = text.align_left)
    table.cell(tb, 1, 5, sHit ? pc(sRes) + " of the time" : "—", text_color = dim, text_size = ts, text_halign = text.align_right)

    table.cell(tb, 0, 6, "OUT OF EVERY 100 RANGES HERE", text_color = dim, text_size = ts, bgcolor = sec, text_halign = text.align_left)
    table.cell(tb, 1, 6, "", text_size = ts, bgcolor = sec)

    table.cell(tb, 0, 7, "close above previous high", text_color = upCol, text_size = ts, text_halign = text.align_left)
    table.cell(tb, 1, 7, pc(uAbove), text_color = sHit and sDir == "U" ? color.teal : tx, text_size = ts, text_halign = text.align_right)

    table.cell(tb, 0, 8, "close below previous low", text_color = dnCol, text_size = ts, text_halign = text.align_left)
    table.cell(tb, 1, 8, pc(uBelow), text_color = sHit and sDir == "D" ? color.maroon : tx, text_size = ts, text_halign = text.align_right)

    table.cell(tb, 0, 9, "close inside — no result", text_color = dim, text_size = ts, text_halign = text.align_left)
    table.cell(tb, 1, 9, pc(uInside), text_color = tx, text_size = ts, text_halign = text.align_right)

    table.cell(tb, 0, 10, detL, text_color = dim, text_size = ts, text_halign = text.align_left)
    table.cell(tb, 1, 10, detR, text_color = dim, text_size = ts, text_halign = text.align_right)

    table.cell(tb, 0, 11, foot, text_color = tooHigh and not showDebug ? color.new(color.orange, 10) : dim, text_size = size.tiny, text_halign = text.align_left)
    table.cell(tb, 1, 11, "", text_size = size.tiny)

    if showOthers
        live = 0
        for i = 0 to 4
            if i != tfIdx and not na(kPr.get(i))
                live += 1
        table.cell(tb, 0, 12, "OTHER RANGE SIZES, LIVE NOW", text_color = dim, text_size = ts, bgcolor = sec, text_halign = text.align_left)
        table.cell(tb, 1, 12, live == 0 ? "none" : str.tostring(live), text_color = dim, text_size = ts, bgcolor = sec, text_halign = text.align_right)
        r = 13
        for i = 0 to 4
            if i != tfIdx
                pr  = kPr.get(i)
                dr  = kDr.get(i)
                rs  = kRs.get(i)
                on  = not na(pr)
                col = not on ? dim : dr == "U" ? color.teal : color.maroon
                txt = not on ? "—" : (dr == "U" ? "▲ " : "▼ ") + str.tostring(pr, "0") + "% · " + str.tostring(rs, "0") + "% res"
                table.cell(tb, 0, r, TFNAME.get(i) + (on ? (dr == "U" ? " above prev high" : " below prev low") : ""), text_color = col, text_size = ts, text_halign = text.align_left)
                table.cell(tb, 1, r, txt, text_color = col, text_size = ts, text_halign = text.align_right)
                r += 1

    if showLive
        nCalls = tClaim.size()
        sumCl  = 0.0
        sumOK  = 0.0
        nRes   = 0
        sumRCl = 0.0
        sumRes = 0.0
        for i = 0 to (nCalls > 0 ? nCalls - 1 : 0)
            if nCalls > 0
                sumRCl += tResCl.get(i)
                sumRes += tResOK.get(i)
                if not na(tOK.get(i))
                    sumCl += tClaim.get(i)
                    sumOK += tOK.get(i)
                    nRes  += 1
        claimAvg = nRes > 0 ? sumCl / nRes : na
        liveAvg  = nRes > 0 ? 100 * sumOK / nRes : na
        gap      = na(liveAvg) ? na : liveAvg - claimAvg
        rClaim   = nCalls > 0 ? sumRCl / nCalls : na
        rLive    = nCalls > 0 ? 100 * sumRes / nCalls : na
        gapCol   = na(gap) ? dim : gap >= -2 ? color.teal : gap >= -7 ? color.new(color.orange, 10) : color.maroon

        table.cell(tb, 0, 17, "ON THIS CHART, LAST " + str.tostring(trackN) + " CALLS", text_color = dim, text_size = ts, bgcolor = sec, text_halign = text.align_left)
        table.cell(tb, 1, 17, str.tostring(nCalls) + " made", text_color = dim, text_size = ts, bgcolor = sec, text_halign = text.align_right)

        table.cell(tb, 0, 18, "resolved / unresolved", text_color = dim, text_size = ts, text_halign = text.align_left)
        table.cell(tb, 1, 18, nCalls == 0 ? "—" : str.tostring(nRes) + " / " + str.tostring(nCalls - nRes), text_color = tx, text_size = ts, text_halign = text.align_right)

        table.cell(tb, 0, 19, "claimed vs actual", text_color = dim, text_size = ts, text_halign = text.align_left)
        table.cell(tb, 1, 19, nRes == 0 ? "—" : pc2(claimAvg) + " vs " + pc2(liveAvg), text_color = tx, text_size = ts, text_halign = text.align_right)

        table.cell(tb, 0, 20, "drift", text_color = dim, text_size = ts, text_halign = text.align_left)
        table.cell(tb, 1, 20, na(gap) ? "—" : (gap >= 0 ? "+" : "") + str.tostring(gap, "0.#") + " pts", text_color = gapCol, text_size = ts, text_halign = text.align_right)

        table.cell(tb, 0, 21, "resolve rate, claimed vs actual", text_color = dim, text_size = ts, text_halign = text.align_left)
        table.cell(tb, 1, 21, nCalls == 0 ? "—" : pc2(rClaim) + " vs " + pc2(rLive), text_color = dim, text_size = ts, text_halign = text.align_right)
""")

    with open(out_file, "w", encoding="utf-8") as f:
        f.write("\n".join(pine_lines))

    print(f"SUCCESS: Created {out_file} ({len(pine_lines)} lines, {os.path.getsize(out_file)/1024:.1f} KB)")


if __name__ == "__main__":
    generate_universal_pine()
