"""
NinjaTrader 8 LUT Data Builder
Reads probability matrices from data/range_prob/matrices/ and generates
a C# RangeProbabilityLutData.cs file with embedded lookup table entries.
"""
import os
import sys
import json
import argparse
from pathlib import Path

def build_lut_data_class(matrices_dir: str, output_path: str, ticker: str = "NQ"):
    """Generate RangeProbabilityLutData.cs from probability matrix JSON files."""
    matrix_file = os.path.join(matrices_dir, f"{ticker.upper()}_matrices.json")

    if not os.path.exists(matrix_file):
        print(f"[WARNING] No matrix file found for {ticker} at {matrix_file}")
        print(f"          Generating placeholder. Run the engine first:")
        print(f"          python -m scripts.range_probability.engine --tickers {ticker}")

        entries_code = "            // PLACEHOLDER -- run build_ninjatrader_lut.py after generating matrices\n"
    else:
        with open(matrix_file, "r", encoding="utf-8") as f:
            matrix_data = json.load(f)

        entries = []
        for tf_str, tf_data in matrix_data.get("intervals", {}).items():
            for rec in tf_data.get("records", []):
                if rec.get("is_qualified", False):
                    slot = rec["slot"]
                    b_char = rec["bucket_char"]
                    direction = rec["direction"]
                    prob_train = rec.get("prob_train", rec.get("prob_full", 50))
                    prob_test = rec.get("prob_test", prob_train)
                    n = min(999, rec["sample_size"])
                    res = min(99, int(round(rec["resolve_rate"])))

                    if prob_train is None or (isinstance(prob_train, float) and prob_train != prob_train):
                        prob_train = rec.get("prob_full", 50)
                    if prob_test is None or (isinstance(prob_test, float) and prob_test != prob_test):
                        prob_test = prob_train

                    p_tr = f"{int(round(prob_train)):03d}"
                    p_te = f"{int(round(prob_test)):03d}"
                    n_str = f"{n:03d}"
                    res_str = f"{res:02d}"

                    key = f"{slot}{b_char}"
                    val = f"{direction}{p_tr}{p_te}{n_str}{res_str}"
                    entries.append((key, val))

        if entries:
            entries_code = ""
            for key, val in entries:
                entries_code += f'            lut["{key}"] = "{val}";\n'
        else:
            entries_code = "            // No qualified cells found in the matrix\n"

    cs_code = f"""// Auto-generated by scripts/range_probability/build_ninjatrader_lut.py
// DO NOT EDIT MANUALLY -- re-run the builder after updating probability matrices.
// Source: {matrix_file}
using System.Collections.Generic;

namespace NinjaTrader.NinjaScript.Indicators
{{
    public static class RangeProbabilityLutData
    {{
        // Each entry: key = slot(4) + bucketChar(1), value = dir(1) + prob(3) + test(3) + N(3) + res(2)
        public static Dictionary<string, string> GetEntries()
        {{
            var lut = new Dictionary<string, string>();
{entries_code}            return lut;
        }}
    }}
}}
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(cs_code)
    print(f"Generated LUT data class: {output_path} ({len(entries) if entries else 0} entries)")


def main():
    parser = argparse.ArgumentParser(description="Build NinjaTrader 8 LUT data class from probability matrices")
    parser.add_argument("--ticker", type=str, default="NQ", help="Ticker to build LUT for")
    parser.add_argument("--matrices-dir", type=str, default="data/range_prob/matrices", help="Directory with matrix JSON files")
    parser.add_argument("--output", type=str, default="scripts/ninjatrader/indicators/range_probability/RangeProbabilityLutData.cs", help="Output C# file path")
    args = parser.parse_args()

    build_lut_data_class(args.matrices_dir, args.output, args.ticker)


if __name__ == "__main__":
    main()