"""
NinjaTrader 8 Multi-Asset LUT Data Builder
Reads all probability matrices from data/range_prob/matrices/
and generates a robust, multi-asset C# RangeProbabilityLutData.cs file.
"""

import os
import sys
import json
from pathlib import Path

def generate_nt8_lut_class():
    matrices_dir = "data/range_prob/matrices"
    out_file = "scripts/ninjatrader/indicators/range_probability/RangeProbabilityLutData.cs"

    tickers = ["NQ", "ES", "YM", "RTY", "CL", "GC", "SPY", "QQQ", "AAPL", "NVDA", "TSLA"]
    intervals = [15, 30, 60, 120, 240]

    all_entries = {} # (ticker, interval) -> list of (key, val)

    for ticker in tickers:
        p = os.path.join(matrices_dir, f"{ticker}_matrices.json")
        if not os.path.exists(p):
            print(f"[SKIP] No matrix JSON for {ticker}")
            continue

        with open(p, "r", encoding="utf-8") as f:
            data = json.load(f)

        for tf_str, tf_data in data.get("intervals", {}).items():
            tf_int = int(tf_str)
            entries_list = []
            for rec in tf_data.get("records", []):
                # We store all cells that have a valid direction and sample size >= 10
                slot = rec["slot"]
                b_char = rec["bucket_char"]
                direction = rec["direction"]
                prob = int(round(rec.get("prob_all", 50)))
                test = int(round(rec.get("prob_test", prob)))
                n = min(999, rec["sample_size"])
                res = min(99, int(round(rec["resolve_rate"])))

                val = f"{direction}{prob:03d}{test:03d}{n:03d}{res:02d}"
                key = f"{slot}{b_char}"
                entries_list.append((key, val))

            all_entries[(ticker, tf_int)] = entries_list

    print(f"Generating NT8 C# LUT class for {len(all_entries)} (ticker, interval) combinations...")

    cs_lines = [
        "// Auto-generated by scripts/range_probability/build_ninjatrader_lut.py",
        "// DO NOT EDIT MANUALLY -- re-run the builder after updating probability matrices.",
        "using System;",
        "using System.Collections.Generic;",
        "",
        "namespace NinjaTrader.NinjaScript.Indicators",
        "{",
        "    public static class RangeProbabilityLutData",
        "    {",
        "        // Dictionary keyed by: \"TICKER_TF_SLOT_BUCKET\"",
        "        // Value: dir(1) + prob(3) + test(3) + N(3) + res(2)",
        "        private static readonly Dictionary<string, string> MasterLut = new Dictionary<string, string>()",
        "        {",
    ]

    for (t, tf), entries in all_entries.items():
        cs_lines.append(f"            // === {t} {tf}m ===")
        for k, v in entries:
            # Combined master key: "NQ_60_10009"
            master_key = f"{t}_{tf}_{k}"
            cs_lines.append(f'            ["{master_key}"] = "{v}",')

    cs_lines.extend([
        "        };",
        "",
        "        public static Dictionary<string, string> GetEntries(string instrument = \"NQ\", int rangeMinutes = 60)",
        "        {",
        "            var lut = new Dictionary<string, string>();",
        "            string instClean = \"NQ\";",
        "            if (!string.IsNullOrEmpty(instrument))",
        "            {",
        "                string upper = instrument.ToUpper();",
        "                if (upper.Contains(\"NQ\") || upper.Contains(\"MNQ\") || upper.Contains(\"USTEC\")) instClean = \"NQ\";",
        "                else if (upper.Contains(\"ES\") || upper.Contains(\"MES\") || upper.Contains(\"SPX\")) instClean = \"ES\";",
        "                else if (upper.Contains(\"YM\") || upper.Contains(\"MYM\") || upper.Contains(\"US30\")) instClean = \"YM\";",
        "                else if (upper.Contains(\"RTY\") || upper.Contains(\"M2K\") || upper.Contains(\"US2000\")) instClean = \"RTY\";",
        "                else if (upper.Contains(\"CL\") || upper.Contains(\"MCL\")) instClean = \"CL\";",
        "                else if (upper.Contains(\"GC\") || upper.Contains(\"MGC\")) instClean = \"GC\";",
        "                else if (upper.Contains(\"SPY\")) instClean = \"SPY\";",
        "                else if (upper.Contains(\"QQQ\")) instClean = \"QQQ\";",
        "                else if (upper.Contains(\"AAPL\")) instClean = \"AAPL\";",
        "                else if (upper.Contains(\"NVDA\")) instClean = \"NVDA\";",
        "                else if (upper.Contains(\"TSLA\")) instClean = \"TSLA\";",
        "                else instClean = \"NQ\";",
        "            }",
        "",
        "            string prefix = instClean + \"_\" + rangeMinutes + \"_\";",
        "            foreach (var kvp in MasterLut)",
        "            {",
        "                if (kvp.Key.StartsWith(prefix))",
        "                {",
        "                    string slotBucket = kvp.Key.Substring(prefix.Length);",
        "                    lut[slotBucket] = kvp.Value;",
        "                }",
        "            }",
        "",
        "            // Fallback to NQ if no entries found for instrument/tf",
        "            if (lut.Count == 0 && instClean != \"NQ\")",
        "            {",
        "                string fbPrefix = \"NQ_\" + rangeMinutes + \"_\";",
        "                foreach (var kvp in MasterLut)",
        "                {",
        "                    if (kvp.Key.StartsWith(fbPrefix))",
        "                    {",
        "                        string slotBucket = kvp.Key.Substring(fbPrefix.Length);",
        "                        lut[slotBucket] = kvp.Value;",
        "                    }",
        "                }",
        "            }",
        "            return lut;",
        "        }",
        "    }",
        "}",
    ])

    os.makedirs(os.path.dirname(out_file), exist_ok=True)
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("\n".join(cs_lines))

    print(f"SUCCESS: Generated {out_file} ({len(cs_lines)} lines, {os.path.getsize(out_file)/1024:.1f} KB)")


if __name__ == "__main__":
    generate_nt8_lut_class()