"""
NinjaTrader 8 High-Performance Typed LUT Data Builder
Reads all probability matrices from data/range_prob/matrices/
and generates a typed, zero-allocation RangeProbabilityLutData.cs file.
"""

import os
import sys
import json
from pathlib import Path

def generate_nt8_lut_class():
    matrices_dir = "data/range_prob/matrices"
    out_file = "scripts/ninjatrader/indicators/range_probability/RangeProbabilityLutData.cs"

    tickers = ["NQ", "ES", "YM", "RTY", "CL", "GC", "SPY", "QQQ", "AAPL", "NVDA", "TSLA"]
    intervals = [15, 30, 60, 120, 240]

    all_entries = {} # (ticker, interval) -> list of (key, dir, prob, test, n, res)

    for ticker in tickers:
        p = os.path.join(matrices_dir, f"{ticker}_matrices.json")
        if not os.path.exists(p):
            continue

        with open(p, "r", encoding="utf-8") as f:
            data = json.load(f)

        for tf_str, tf_data in data.get("intervals", {}).items():
            tf_int = int(tf_str)
            entries_list = []
            for rec in tf_data.get("records", []):
                slot = rec["slot"]
                b_char = rec["bucket_char"]
                direction = rec["direction"]
                prob = int(round(rec.get("prob_all", 50)))
                test = int(round(rec.get("prob_test", prob)))
                n = min(999, rec["sample_size"])
                res = min(99, int(round(rec["resolve_rate"])))

                key = f"{slot}{b_char}"
                dir_char = direction[0] if direction in ["UP", "DOWN", "U", "D"] else "N"
                if dir_char == "D" and direction == "DOWN":
                    dir_char = "D"
                elif dir_char == "U" and direction == "UP":
                    dir_char = "U"
                entries_list.append((key, dir_char, prob, test, n, res))

            all_entries[(ticker, tf_int)] = entries_list

    print(f"Generating NT8 Typed LUT class for {len(all_entries)} (ticker, interval) combinations...")

    cs_lines = [
        "// Auto-generated by scripts/range_probability/build_ninjatrader_lut.py",
        "// DO NOT EDIT MANUALLY -- re-run the builder after updating probability matrices.",
        "using System;",
        "using System.Collections.Generic;",
        "",
        "namespace NinjaTrader.NinjaScript.Indicators",
        "{",
        "    public struct RangeLutCell",
        "    {",
        "        public char Dir;",
        "        public byte Prob;",
        "        public byte Test;",
        "        public short N;",
        "        public byte Res;",
        "",
        "        public RangeLutCell(char dir, byte prob, byte test, short n, byte res)",
        "        {",
        "            Dir = dir;",
        "            Prob = prob;",
        "            Test = test;",
        "            N = n;",
        "            Res = res;",
        "        }",
        "    }",
        "",
        "    public static class RangeProbabilityLutData",
        "    {",
        "        // Dictionary keyed by \"TICKER_TF\" -> (slot+bucket -> RangeLutCell)",
        "        private static readonly Dictionary<string, Dictionary<string, RangeLutCell>> MasterLut = new Dictionary<string, Dictionary<string, RangeLutCell>>()",
        "        {",
    ]

    for (t, tf), entries in all_entries.items():
        master_key = f"{t}_{tf}"
        cs_lines.append(f'            ["{master_key}"] = new Dictionary<string, RangeLutCell>()')
        cs_lines.append("            {")
        for k, d, p, te, n, res in entries:
            cs_lines.append(f"                [\"{k}\"] = new RangeLutCell('{d}', {p}, {te}, {n}, {res}),")
        cs_lines.append("            },")

    cs_lines.extend([
        "        };",
        "",
        "        public static Dictionary<string, RangeLutCell> GetEntries(string instrument = \"NQ\", int rangeMinutes = 60)",
        "        {",
        "            string instClean = \"NQ\";",
        "            if (!string.IsNullOrEmpty(instrument))",
        "            {",
        "                string upper = instrument.ToUpper();",
        "                if (upper.Contains(\"MNQ\") || upper.Contains(\"NQ\") || upper.Contains(\"USTEC\") || upper.Contains(\"NAS100\")) instClean = \"NQ\";",
        "                else if (upper.Contains(\"MES\") || upper.Contains(\"ES\") || upper.Contains(\"SPX\") || upper.Contains(\"US500\")) instClean = \"ES\";",
        "                else if (upper.Contains(\"MYM\") || upper.Contains(\"YM\") || upper.Contains(\"US30\") || upper.Contains(\"DOW\")) instClean = \"YM\";",
        "                else if (upper.Contains(\"M2K\") || upper.Contains(\"RTY\") || upper.Contains(\"US2000\") || upper.Contains(\"RUSSELL\")) instClean = \"RTY\";",
        "                else if (upper.Contains(\"MCL\") || upper.Contains(\"CL\") || upper.Contains(\"CRUDE\") || upper.Contains(\"WTI\")) instClean = \"CL\";",
        "                else if (upper.Contains(\"MGC\") || upper.Contains(\"GC\") || upper.Contains(\"GOLD\")) instClean = \"GC\";",
        "                else if (upper.Contains(\"SPY\")) instClean = \"SPY\";",
        "                else if (upper.Contains(\"QQQ\")) instClean = \"QQQ\";",
        "                else if (upper.Contains(\"AAPL\")) instClean = \"AAPL\";",
        "                else if (upper.Contains(\"NVDA\")) instClean = \"NVDA\";",
        "                else if (upper.Contains(\"TSLA\")) instClean = \"TSLA\";",
        "                else instClean = \"NQ\";",
        "            }",
        "",
        "            string key = instClean + \"_\" + rangeMinutes;",
        "            if (MasterLut.TryGetValue(key, out var dict))",
        "            {",
        "                return dict;",
        "            }",
        "",
        "            // Fallback to NQ_60 if not found",
        "            if (MasterLut.TryGetValue(\"NQ_\" + rangeMinutes, out var fbDict))",
        "            {",
        "                return fbDict;",
        "            }",
        "",
        "            return new Dictionary<string, RangeLutCell>();",
        "        }",
        "    }",
        "}",
    ])

    os.makedirs(os.path.dirname(out_file), exist_ok=True)
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("\n".join(cs_lines))

    print(f"SUCCESS: Generated {out_file} ({len(cs_lines)} lines, {os.path.getsize(out_file)/1024:.1f} KB)")


if __name__ == "__main__":
    generate_nt8_lut_class()