"""
Matrix Store & Serializer
Handles exporting and loading of Range Probability matrices across tickers and intervals.
Supports JSON, CSV, Parquet, and Pine Script v6 lookup table string blocks.
"""

import os
import json
from datetime import datetime
from typing import Dict, List, Any, Optional
import numpy as np
import pandas as pd


class MatrixStore:
    def __init__(self, base_dir: str = "data/range_prob"):
        self.base_dir = base_dir
        self.matrices_dir = os.path.join(base_dir, "matrices")
        self.pine_dir = os.path.join(base_dir, "pine_lut")
        self.feeds_dir = os.path.join(base_dir, "backtest_feeds")
        self.reports_dir = os.path.join(base_dir, "reports")

        for d in [self.matrices_dir, self.pine_dir, self.feeds_dir, self.reports_dir]:
            os.makedirs(d, exist_ok=True)

    def save_matrix(self, ticker: str, matrix_data: Dict[str, Any]) -> str:
        """Saves matrix data to JSON."""
        filename = f"{ticker.upper()}_matrices.json"
        path = os.path.join(self.matrices_dir, filename)

        def json_default(obj):
            if isinstance(obj, (np.bool_, bool)):
                return bool(obj)
            if isinstance(obj, (np.integer, int)):
                return int(obj)
            if isinstance(obj, (np.floating, float)):
                return float(obj)
            if isinstance(obj, (pd.Timestamp, datetime)):
                return obj.isoformat()
            return str(obj)

        with open(path, "w", encoding="utf-8") as f:
            json.dump(matrix_data, f, indent=2, default=json_default)
        return path

    def load_matrix(self, ticker: str) -> Optional[Dict[str, Any]]:
        """Loads matrix data from JSON."""
        path = os.path.join(self.matrices_dir, f"{ticker.upper()}_matrices.json")
        if not os.path.exists(path):
            return None
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

    def export_pine_script_luts(self, ticker: str, intervals_data: Dict[int, Dict[str, Any]]) -> str:
        """
        Generates Pine Script v6 formatted D15, D30, D60, D120, D240 constants.
        """
        lines = [
            f"// Range Probability Lookup Tables for {ticker.upper()}",
            "// Auto-generated by Antigravity Range Probability Engine",
            "",
        ]

        tf_var_names = {15: "D15", 30: "D30", 60: "D60", 120: "D120", 240: "D240"}

        for tf, var_name in tf_var_names.items():
            if tf in intervals_data:
                lut_str = intervals_data[tf].get("pine_lut_string", "")
            else:
                lut_str = ""

            # Split lut_str into lines of ~100-110 chars for clean readability in Pine Script
            if not lut_str:
                lines.append(f'{var_name} = ""')
            else:
                chunk_len = 102 # 6 records of 17 chars
                chunks = [lut_str[i:i + chunk_len] for i in range(0, len(lut_str), chunk_len)]
                lines.append(f'{var_name} = "{chunks[0]}"')
                for ch in chunks[1:]:
                    lines.append(f'  + "{ch}"')
            lines.append("")

        out_path = os.path.join(self.pine_dir, f"{ticker.upper()}_lut.pine")
        with open(out_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        return out_path

    def export_summary_report(self, all_ticker_summaries: List[Dict[str, Any]]) -> str:
        """Exports a consolidated CSV report comparing all tickers and intervals."""
        df = pd.DataFrame(all_ticker_summaries)
        out_path = os.path.join(self.reports_dir, "summary_all_tickers.csv")
        df.to_csv(out_path, index=False)
        return out_path
