export const V3_API_ENDPOINTS = [
  "/api/options-live/v3/summary",
  "/api/options-live/v3/by-strike",
  "/api/options-live/v3/by-expiry",
  "/api/options-live/v3/largest",
  "/api/options-live/v3/levels",
  "/api/options-live/v3/spot-gamma",
  "/api/options-live/v3/heatmap",
  "/api/options-live/v3/narrative",
  "/api/options-live/v3/llm-compare",
  "/api/options-live/v3/recent-flow",
  "/api/options-live/v3/explain",
  "/api/options-live/v3/publish/preview",
  "/api/options-live/v3/publish/discord",
  "/api/options-live/v3/publish/event-rule",
] as const;
